module.exports = {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./public/assets/js/**/*.js",
    ],
    css: [
        "./public/assets/vendor/bootstrap/css/bootstrap.min.css",
        "./public/assets/css/main.css",
        "./public/assets/vendor/bootstrap-icons/bootstrap-icons.css",
    ],
    output: "./public/assets/css/purged/",
    safelist: [
        // Keep critical classes
        "container",
        "row",
        "col-*",
        "d-*",
        "text-*",
        "bg-*",
        "btn-*",
        "form-*",
        "nav-*",
        "navbar-*",
        "card-*",
        "hero",
        "section",
        "header",
        "footer",
        "main",
        // Keep animation classes
        "fade",
        "show",
        "active",
        "collapse",
        "collapsing",
        // Keep responsive utilities
        "w-*",
        "h-*",
        "m-*",
        "p-*",
        "mx-*",
        "my-*",
        "px-*",
        "py-*",
        // Keep Bootstrap Icons
        "bi",
        "bi-*",
        // Keep custom classes
        /^whatsapp-/,
        /^youtube-/,
        /^course-/,
        /^testimonial-/,
        /^hero-/,
        /^navmenu/,
        /^mobile-/,
        /^contact-/,
    ],
    defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
    fontFace: true,
    keyframes: true,
    variables: true,
};
