<?php

/**
 * Cloudinary Image Mappings
 * 
 * This file stores mappings between local asset paths and Cloudinary URLs.
 * Generated by: php artisan cloudinary:upload-home-images
 */

return array (
  'assets/img/hero-bg-1.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764334/home/home/assets_img_hero-bg-1.webp',
  'assets/img/hero-bg-4.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764336/home/home/assets_img_hero-bg-4.webp',
  'assets/img/about.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764338/home/home/assets_img_about.webp',
  'assets/img/about-bg.png' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764340/home/home/assets_img_about-bg.png',
  'assets/img/choos-us.png' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764342/home/home/assets_img_choos-us.png',
  'assets/img/ai/course-1.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764345/home/home/assets_img_ai_course-1.webp',
  'assets/img/ai/course-2.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764347/home/home/assets_img_ai_course-2.webp',
  'assets/img/ai/course-3.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764362/home/home/assets_img_ai_course-3.webp',
  'assets/img/ai/course-4.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764369/home/home/assets_img_ai_course-4.webp',
  'assets/img/ai/thumbsup1.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764370/home/home/assets_img_ai_thumbsup1.webp',
  'assets/img/ai/contact-us.jpg' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764373/home/home/assets_img_ai_contact-us.jpg',
  'assets/img/icons/pointing-up.avif' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764377/home/home/assets_img_icons_pointing-up.avif',
  'assets/img/icons/schedule.avif' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764379/home/home/assets_img_icons_schedule.avif',
  'assets/img/icons/koran.avif' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764381/home/home/assets_img_icons_koran.avif',
  'assets/img/icons/quality.avif' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764382/home/home/assets_img_icons_quality.avif',
  'assets/img/logo.svg' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764765039/home/home/logo.svg',
  'assets/img/logo.png' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764721/home/home/assets_img_logo.png',
  'assets/img/header-bg.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764722/home/home/assets_img_header-bg.webp',
  'assets/img/tab-logo.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764724/home/home/assets_img_tab-logo.webp',
  'assets/img/ai/about-1.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764726/home/home/assets_img_ai_about-1.webp',
  'assets/img/ai/about.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764727/home/home/assets_img_ai_about.webp',
  'assets/img/ai/our-mission.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764729/home/home/assets_img_ai_our-mission.webp',
  'assets/img/hero-bg-3.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764731/home/home/assets_img_hero-bg-3.webp',
  'assets/img/ai/teacher-1.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764734/home/home/assets_img_ai_teacher-1.webp',
  'assets/img/ai/teachers.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764737/home/home/assets_img_ai_teachers.webp',
  'assets/img/ai/test-1.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764741/home/home/assets_img_ai_test-1.webp',
  'assets/img/ai/test-2.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764752/home/home/assets_img_ai_test-2.webp',
  'assets/img/ai/test-3.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764770/home/home/assets_img_ai_test-3.webp',
  'assets/img/ai/test-4.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764784/home/home/assets_img_ai_test-4.webp',
  'assets/img/ai/test-5.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764786/home/home/assets_img_ai_test-5.webp',
  'assets/img/ai/happystudent.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764788/home/home/assets_img_ai_happystudent.webp',
  'assets/img/video-thumb.webp' => 'https://res.cloudinary.com/ddkmwga8q/image/upload/v1764764790/home/home/assets_img_video-thumb.webp',
);
