<?php

return [
    'currencies' => [
        'USD' => ['name' => 'US Dollar', 'symbol' => '$', 'code' => 'USD'],
        'EUR' => ['name' => 'Euro', 'symbol' => '€', 'code' => 'EUR'],
        'GBP' => ['name' => 'British Pound', 'symbol' => '£', 'code' => 'GBP'],
        'PKR' => ['name' => 'Pakistani Rupee', 'symbol' => '₨', 'code' => 'PKR'],
        'SAR' => ['name' => 'Saudi Riyal', 'symbol' => '﷼', 'code' => 'SAR'],
        'AED' => ['name' => 'UAE Dirham', 'symbol' => 'د.إ', 'code' => 'AED'],
        'CAD' => ['name' => 'Canadian Dollar', 'symbol' => 'C$', 'code' => 'CAD'],
        'AUD' => ['name' => 'Australian Dollar', 'symbol' => 'A$', 'code' => 'AUD'],
        'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹', 'code' => 'INR'],
        'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥', 'code' => 'JPY'],
        'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥', 'code' => 'CNY'],
        'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => 'NZ$', 'code' => 'NZD'],
        'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'CHF', 'code' => 'CHF'],
        'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr', 'code' => 'SEK'],
        'NOK' => ['name' => 'Norwegian Krone', 'symbol' => 'kr', 'code' => 'NOK'],
        'DKK' => ['name' => 'Danish Krone', 'symbol' => 'kr', 'code' => 'DKK'],
    ],

    'country_to_currency' => [
        'United States of America' => 'USD',
        'USA' => 'USD',
        'United Kingdom' => 'GBP',
        'UK' => 'GBP',
        'Pakistan' => 'PKR',
        'Saudi Arabia' => 'SAR',
        'United Arab Emirates' => 'AED',
        'UAE' => 'AED',
        'Canada' => 'CAD',
        'Australia' => 'AUD',
        'New Zealand' => 'NZD',
        'India' => 'INR',
        'Japan' => 'JPY',
        'China' => 'CNY',
        'Switzerland' => 'CHF',
        'Sweden' => 'SEK',
        'Norway' => 'NOK',
        'Denmark' => 'DKK',
        'Germany' => 'EUR',
        'France' => 'EUR',
        'Italy' => 'EUR',
        'Spain' => 'EUR',
        'Netherlands' => 'EUR',
        'Belgium' => 'EUR',
        'Austria' => 'EUR',
        'Portugal' => 'EUR',
        'Greece' => 'EUR',
        'Ireland' => 'EUR',
        'Finland' => 'EUR',
        'Luxembourg' => 'EUR',
        // Add more mappings as needed
    ],

    'default_currency' => 'USD',
];

