<?php

/**
 * Source data for 100 UK Quran landing pages.
 * Each location has unique local copy so pages are not doorway/thin duplicates.
 */

if (! function_exists('rq_uk_loc')) {
    function rq_uk_loc(array $d): array
    {
        return [
            'slug' => $d[0],
            'name' => $d[1],
            'kind' => $d[2], // city | london_borough
            'region' => $d[3],
            'featured' => $d[4],
            'areas' => $d[5],
            'community' => $d[6],
            'intro' => $d[7],
            'need' => $d[8],
            'teaching' => $d[9],
            'audience' => $d[10],
            'focus' => $d[11],
            'faqs' => $d[12],
        ];
    }
}

return [

    rq_uk_loc(['london', 'London', 'city', 'Greater London', true,
        ['Whitechapel', 'East Ham', 'Wembley', 'Tooting', 'Ilford', 'Edgware'],
        'London has the United Kingdom’s largest and most diverse Muslim population, with long-established Pakistani, Bangladeshi, Somali, Arab, and Turkish communities across every compass point of the capital.',
        'Families in London want Quran classes that respect busy Tube commutes, after-school clubs, and the mix of languages spoken at home. Rooh Ul Quran Academy runs live one-to-one lessons so a child in Tower Hamlets and a professional in Ealing can learn at a time that actually fits London life.',
        'Parents here often struggle to find a consistent local madrasa slot, especially when work finishes late in the City or West End. Online Tajweed and Hifz with a dedicated tutor removes the school-run clash without lowering recitation standards.',
        'We match London students with male or female tutors, keep UK evening availability, and track progress weekly so parents can see real improvement in makharij, fluency, and memorisation.',
        'Kids after school, sisters who prefer a female teacher, and adults correcting long-held recitation habits',
        'tajweed',
        [
            ['q' => 'Do you follow UK school-term evenings for London students?', 'a' => 'Yes. Most London families book after 4:30pm GMT/BST, plus weekend mornings. We also keep a few early slots for parents who work late shifts in hospitality or the NHS.'],
            ['q' => 'Can siblings in different London boroughs share a family plan?', 'a' => 'They can enrol together with staggered times. Each child still gets a private tutor so a Year 3 beginner and a Hifz student are not forced into the same lesson.'],
            ['q' => 'Is the class useful if we already attend a mosque in London at weekends?', 'a' => 'Many London students use our weekday sessions to lock Tajweed between jumu’ah and Sunday madrasa, so mosque homework becomes easier rather than duplicated.'],
        ],
    ]),

    rq_uk_loc(['birmingham', 'Birmingham', 'city', 'West Midlands', true,
        ['Sparkhill', 'Small Heath', 'Alum Rock', 'Aston', 'Washwood Heath', 'Bordesley Green'],
        'Birmingham is one of Britain’s most important Muslim cities. Pakistani, Kashmiri, Yemeni, and Somali families are woven into the city’s schools, mosques, and high streets from Sparkhill through to Aston.',
        'In Birmingham, Quran learning is part of family identity, not a weekend extra. Rooh Ul Quran Academy offers live online classes that sit around Birmingham school hours, mosque clubs, and the long working days common in the city’s retail and taxi trades.',
        'Large families here often need more than one child in class at once, plus sisters who want a female tutor. Local madrasas can have waiting lists; a dedicated online teacher keeps Hifz and Qaida moving without a 40-minute drive across the ring road.',
        'Lessons are one-to-one, with clear Hifz revision cycles and Tajweed correction that Birmingham parents can review after each session.',
        'Primary-age beginners, teenage Hifz students, and mothers restarting recitation',
        'hifz',
        [
            ['q' => 'Can Birmingham students start Hifz while still in mainstream school?', 'a' => 'Yes. We set a realistic daily new-lesson plus revision plan that respects homework and Friday mosque time, rather than an unrealistic full-time hifz load.'],
            ['q' => 'Do you have female teachers for Sparkhill and Small Heath families?', 'a' => 'Female tutors are available for girls and for mothers who prefer to learn privately at home.'],
            ['q' => 'What time zone do Birmingham classes use?', 'a' => 'Europe/London. Evening slots after school are the most popular, with Saturday morning options for working fathers.'],
        ],
    ]),

    rq_uk_loc(['bradford', 'Bradford', 'city', 'West Yorkshire', true,
        ['Manningham', 'Great Horton', 'BD3', 'BD8', 'Keighley Road corridor', 'Toller'],
        'Bradford has one of the highest Muslim population shares of any UK city, with deep Kashmiri and Pakistani roots and a dense network of mosques and supplementary schools.',
        'Bradford families often want Quran teachers who understand Yorkshire school calendars, community events, and the importance of accurate recitation for children who already hear Qur’an at home. Our online academy gives each student a private tutor instead of a crowded classroom.',
        'Waiting lists at popular Bradford madrasas, plus winter evenings and busy mill-town work patterns, make a fixed local slot hard to keep. Live video classes mean a child in Manningham can still complete Qaida or Hifz on nights when the family cannot leave the house.',
        'We emphasise makharij, slow fluency, and parent updates in plain English so Bradford households can support revision between lessons.',
        'Children in primary school, sisters, and adults who recited as children and want to repair Tajweed',
        'qaida',
        [
            ['q' => 'Are classes suitable if our child already attends a Bradford madrasa?', 'a' => 'Yes. We use online time for Tajweed precision and memorisation review, and we avoid overloading the same surahs the madrasa set that week unless you ask us to reinforce them.'],
            ['q' => 'Do teachers understand Bradford family schedules?', 'a' => 'Tutors plan around UK evenings, jumu’ah, and school holidays rather than overseas office hours.'],
            ['q' => 'Can grandparents in Bradford sit in on a trial?', 'a' => 'Parents or grandparents are welcome to observe the free trial so they can judge the teacher’s adab and method.'],
        ],
    ]),

    rq_uk_loc(['manchester', 'Manchester', 'city', 'Greater Manchester', true,
        ['Cheetham Hill', 'Rusholme', 'Longsight', 'Levenshulme', 'Whalley Range', 'Crumpsall'],
        'Manchester’s Muslim community stretches from the curry mile to Cheetham Hill and the wider Greater Manchester boroughs, with students balancing university, NHS shifts, and busy family life.',
        'Rooh Ul Quran Academy serves Manchester with live 1-1 Quran classes timed for UK evenings. Whether you live near Rusholme or commute into the city from Oldham or Bolton, you get a dedicated tutor rather than a shared hall.',
        'University terms, night shifts, and Saturday family commitments make a single mosque timetable awkward. Online Tajweed, Qaida, and Hifz let Manchester students keep a weekly rhythm even during exam season.',
        'We set measurable recitation goals, record homework clearly, and offer female tutors for sisters across Greater Manchester.',
        'University students, young families, and professionals who missed structured Tajweed as children',
        'tajweed',
        [
            ['q' => 'Can a student at a Manchester university keep classes during exams?', 'a' => 'Yes. We pause or shorten lessons during peak exam weeks and rebuild the plan afterwards so Hifz is not abandoned.'],
            ['q' => 'Do you teach adults in Longsight or Cheetham Hill who work evenings?', 'a' => 'Early UK morning and later-night slots can be arranged when tutors are available, alongside standard after-school times.'],
            ['q' => 'Is a free trial available in Manchester time?', 'a' => 'The trial is booked in GMT/BST so you are not asked to join in the middle of the Manchester working day unless you choose that.'],
        ],
    ]),

    rq_uk_loc(['leicester', 'Leicester', 'city', 'East Midlands', true,
        ['Highfields', 'Evington', 'Spinney Hills', 'Belgrave', 'St Matthews', 'North Evington'],
        'Leicester is among the UK cities with the largest Muslim communities relative to its size, with Gujarati, Indian, Pakistani, and Somali families concentrated around Highfields and Evington.',
        'Leicester households often want Quran education that sits beside Saturday Gujarati or community classes and the city’s early school finish. Our tutors work one-to-one so a child is not lost in a large madrasa row.',
        'Parents tell us the hardest part is consistency after school when siblings have different mosque times. A private online teacher lets each child in a Leicester home follow Qaida, Tajweed, or Hifz at their own pace.',
        'We keep lessons short and focused, with extra care for beginners who are still blending English phonics with Arabic letters.',
        'Primary children, sisters, and new Muslims in the city',
        'kids',
        [
            ['q' => 'Do you teach Noorani Qaida for Leicester beginners?', 'a' => 'Yes. Most Leicester children start with Qaida and letter recognition before moving to Quran reading with Tajweed.'],
            ['q' => 'Can mothers in Highfields learn separately from their children?', 'a' => 'Mothers can book their own female-tutor slot, often while children are in school.'],
            ['q' => 'Are classes in English or Arabic explanation?', 'a' => 'Instruction is in clear English with Arabic recitation. Urdu support can be requested when a matching tutor is free.'],
        ],
    ]),

    rq_uk_loc(['luton', 'Luton', 'city', 'Bedfordshire', true,
        ['Bury Park', 'Dallow', 'Saints', 'Challney', 'Farley', 'Leagrave'],
        'Luton has one of the highest proportions of Muslim residents in England, with a well-known community around Bury Park and Dallow and strong Pakistani and Kashmiri family networks.',
        'Luton parents want Quran classes that survive airport-shift work, M1 commuting, and packed after-school hours. Rooh Ul Quran Academy provides live online Tajweed and Hifz with a single assigned teacher.',
        'Local supplementary schools fill quickly. Online lessons mean a family in Bury Park can still give each child a quiet, focused recitation slot at home, even when the second parent is on a late shift.',
        'We plan around UK time, offer female teachers, and send short weekly notes so both parents can follow progress.',
        'School-age children, Hifz hopefuls, and adults correcting recitation',
        'hifz',
        [
            ['q' => 'Can Luton shift workers book weekend-only Quran classes?', 'a' => 'Weekend blocks are available. We prefer two shorter weekly sessions where possible because Hifz sticks better than a single long Saturday class.'],
            ['q' => 'Do you cover Tajweed for children who already read fluently?', 'a' => 'Yes. Fluent readers from Luton madrasas often still need ghunnah, madd, and makharij cleaned up in one-to-one time.'],
            ['q' => 'Is the trial class held on UK time?', 'a' => 'Always. You will not be asked to join in the middle of a Luton school day unless you request it.'],
        ],
    ]),

    rq_uk_loc(['blackburn', 'Blackburn', 'city', 'Lancashire', true,
        ['Bastwell', 'Audley', 'Whalley Range', 'Queen’s Park', 'Little Harwood', 'Daisyfield'],
        'Blackburn with Darwen has one of the largest Muslim population shares in England. Mosques and family networks in Bastwell, Audley, and Little Harwood make Quran education a central part of childhood.',
        'Blackburn families usually want disciplined Hifz and Tajweed without adding another car journey across town after school. Our online academy assigns one tutor who learns each child’s voice, weaknesses, and revision pattern.',
        'Winter weather, large sibling groups, and busy mill-town work hours interrupt physical madrasa attendance. A live video class keeps Qaida and memorisation moving from the dining table.',
        'Teachers emphasise respect, slow recitation, and parent-visible homework, which Blackburn households tell us they value more than flashy apps.',
        'Hifz-age children, sisters, and fathers who want to lead tarawih more confidently',
        'hifz',
        [
            ['q' => 'Do Blackburn students need extra equipment?', 'a' => 'A phone or laptop with a stable connection is enough. A cheap headset helps the tutor hear noon sakinah and qalqalah clearly.'],
            ['q' => 'Can three siblings in one Blackburn house take consecutive slots?', 'a' => 'Yes. Consecutive family slots are common so the device stays set up and parents supervise easily.'],
            ['q' => 'Will the teacher push too much new Hifz too fast?', 'a' => 'No. New lesson size is based on how solid last week’s revision was, not on a race against another child.'],
        ],
    ]),

    rq_uk_loc(['slough', 'Slough', 'city', 'Berkshire', true,
        ['Chalvey', 'Cippenham', 'Langley', 'Upton', 'Wexham', 'Colnbrook'],
        'Slough has a notably high Muslim population for a Berkshire town, with Pakistani, Indian, and Somali families living close to Heathrow shift patterns and London commuter rail.',
        'Slough parents often juggle Crossrail/Elizabeth line commutes and need Quran lessons that start after the school run, not at a time designed for another country. Rooh Ul Quran Academy books live UK-evening classes.',
        'Many children already attend weekend mosque. Weekday online Tajweed fills the gap so recitation does not stall between Saturdays.',
        'We offer female tutors, beginner Qaida, and structured Hifz with weekly parent summaries.',
        'Commuter families, sisters, and children in primary school',
        'tajweed',
        [
            ['q' => 'Can we book immediately after the Slough school run?', 'a' => 'After-school UK slots are the default. We also keep some later evenings for parents returning from London offices.'],
            ['q' => 'Do you teach children who mix English and Urdu at home?', 'a' => 'Yes. Tutors explain rules in simple English and can support Urdu-speaking parents when available.'],
            ['q' => 'Is Slough treated as London time?', 'a' => 'Slough uses the same UK timezone as London. There is no overseas time conversion for local families.'],
        ],
    ]),

    rq_uk_loc(['leeds', 'Leeds', 'city', 'West Yorkshire', true,
        ['Harehills', 'Beeston', 'Hyde Park', 'Chapel Allerton', 'Armley', 'Headingley'],
        'Leeds has a substantial Muslim community across Harehills, Beeston, and Hyde Park, including Pakistani, Kurdish, and student populations linked to the universities.',
        'Leeds families and students want Quran classes that survive university deadlines and Yorkshire school terms. Our one-to-one online model is built for that calendar, not a generic international timetable.',
        'Student houses in Headingley and family homes in Harehills have very different routines. A private tutor adapts the plan instead of forcing everyone into one mosque hall speed.',
        'We teach Qaida through to Hifz and Tajweed repair, with female teachers for sisters in the city.',
        'University students, young families, and teenagers',
        'tajweed',
        [
            ['q' => 'Can Leeds university students take late UK evening classes?', 'a' => 'Yes, subject to tutor availability. Many students prefer 8–10pm after lectures and part-time work.'],
            ['q' => 'Do you help children who attend a Leeds mosque at weekends only?', 'a' => 'Weekday online lessons are designed exactly for that pattern: mosque on Saturday, precision Tajweed online during the week.'],
            ['q' => 'Are trial classes free for Leeds residents?', 'a' => 'The free trial is open to every UK city we list, including Leeds.'],
        ],
    ]),

    rq_uk_loc(['sheffield', 'Sheffield', 'city', 'South Yorkshire', true,
        ['Burngreave', 'Darnall', 'Page Hall', 'Broomhall', 'Nether Edge', 'Firth Park'],
        'Sheffield’s Muslim communities in Burngreave, Darnall, and Page Hall include Pakistani, Yemeni, and Somali families, alongside a large student population.',
        'Sheffield parents want recitation teaching that is patient with Yorkshire school accents and with children who already know some Quran but rush the letters. Online 1-1 classes let the tutor slow the student down properly.',
        'Hills, winter weather, and split-site school days make an extra evening journey tiring. Learning from home keeps Hifz and Qaida consistent through the darker months.',
        'We combine Tajweed drills with short meaning notes so older Sheffield students stay engaged.',
        'Primary children, teenagers, and adult beginners',
        'qaida',
        [
            ['q' => 'Do you teach Yemeni and Somali families in Sheffield as well as Pakistani households?', 'a' => 'Yes. Classes are in English with Arabic recitation. The method does not assume one community’s madrasa background.'],
            ['q' => 'Can a Sheffield student join from a tablet?', 'a' => 'Tablets and phones work. Landscape mode and a stand make it easier for the teacher to see lip and tongue position.'],
            ['q' => 'How do you handle missed lessons in winter?', 'a' => 'We reschedule within the same UK week when possible so Hifz revision does not skip a full cycle.'],
        ],
    ]),

    rq_uk_loc(['bolton', 'Bolton', 'city', 'Greater Manchester', true,
        ['Farnworth', 'Rumworth', 'Deane', 'Great Lever', 'Halliwell', 'Astley Bridge'],
        'Bolton has a well-established Muslim population, especially Indian and Pakistani Gujarati families in Rumworth, Deane, and Great Lever, with a strong mosque and supplementary-school culture.',
        'Bolton parents typically want structured Qaida and Hifz that respects Gujarati community evenings and UK school nights. Rooh Ul Quran Academy assigns one tutor who stays with the child rather than rotating substitutes.',
        'Many children already attend madrasa; they still need private Tajweed time because group classes cannot stop for every mistake. Online lessons fill that precision gap.',
        'We report progress in language parents can share with grandparents who care deeply about recitation quality.',
        'Children, sisters, and adults returning to Quran after years away',
        'qaida',
        [
            ['q' => 'Can Bolton children continue their existing madrasa syllabus with you?', 'a' => 'We can reinforce the same Juz or Qaida lesson on request, or run a separate Tajweed track if you prefer not to mix homework.'],
            ['q' => 'Do you offer female teachers in Bolton?', 'a' => 'Yes, for girls and for mothers who want a private home class.'],
            ['q' => 'What is the typical lesson length?', 'a' => 'Most Bolton children do 30 minutes; older Hifz students often book 45 minutes.'],
        ],
    ]),

    rq_uk_loc(['coventry', 'Coventry', 'city', 'West Midlands', true,
        ['Foleshill', 'Hillfields', 'Stoke', 'Edgwick', 'Upper Stoke', 'Cheylesmore'],
        'Coventry’s Muslim community is concentrated around Foleshill and Hillfields, with Pakistani, Indian, and Somali families and a growing student population at the city’s universities.',
        'Coventry households need Quran classes that work around factory shifts, university labs, and school clubs. Live online teaching gives each student a private recitation coach in UK time.',
        'Local madrasa places can be limited for younger children. Starting Qaida online means a Coventry five-year-old does not wait a term to begin letters.',
        'Tutors keep lessons calm and repetitive where needed, which helps children who get lost in noisy group settings.',
        'Beginners, sisters, and university students',
        'kids',
        [
            ['q' => 'Is Coventry in the same timezone as Birmingham classes?', 'a' => 'Yes. Both use UK time. A Coventry family can book the same evening window as a Birmingham cousin.'],
            ['q' => 'Can students at Coventry University join from campus?', 'a' => 'Yes, if they have headphones and a quiet corner. We recommend not joining from a busy library walkway.'],
            ['q' => 'Do you teach Tajweed to adults who grew up in Coventry but never learned rules?', 'a' => 'Adult Tajweed repair is a common request. We start from the student’s current recitation, not from a child’s Qaida unless needed.'],
        ],
    ]),

    rq_uk_loc(['oldham', 'Oldham', 'city', 'Greater Manchester', true,
        ['Glodwick', 'Westwood', 'Coldhurst', 'Werneth', 'Copster Hill', 'Alexandra'],
        'Oldham has a large Pakistani-heritage Muslim community, particularly in Glodwick, Westwood, and Coldhurst, with Quran education treated as a core family duty.',
        'Oldham parents want teachers who will not rush a child through Juz after Juz without revision. Our Hifz and Tajweed plans are built on repetition that sticks, delivered live online in UK evenings.',
        'After-school traffic between Oldham and Manchester makes a second trip to madrasa exhausting. Home-based live classes protect both recitation quality and family time.',
        'We share simple revision lists so older siblings can listen to the younger child’s sabaq.',
        'Primary children, Hifz students, and mothers',
        'hifz',
        [
            ['q' => 'Do you set daily sabaq for Oldham Hifz students?', 'a' => 'Yes. Each child gets a new lesson size plus a revision map. Parents see it after class.'],
            ['q' => 'Can the teacher hear mistakes clearly over a phone in a busy Oldham home?', 'a' => 'A headset and a quieter room help. We will pause the lesson rather than guess at a letter we cannot hear.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes, including for girls who have started secondary school and prefer a sister teacher.'],
        ],
    ]),

    rq_uk_loc(['rochdale', 'Rochdale', 'city', 'Greater Manchester', true,
        ['Milkstone', 'Deeplish', 'Spotland', 'Castleton', 'Wardleworth', 'Sudden'],
        'Rochdale’s Muslim community, especially around Milkstone and Deeplish, is one of Greater Manchester’s best known, with Kashmiri and Pakistani families and busy mosque networks.',
        'Rochdale families often already have madrasa in the diary. They come to us when they want cleaner Tajweed, a Hifz plan that does not collapse in Year 6 SATs season, or a female teacher for their daughters.',
        'Evening buses and wet Pennine weather make attendance patchy. Online live lessons keep the week intact.',
        'Tutors speak plainly, correct firmly but kindly, and keep parents in the loop without academic jargon.',
        'School children, sisters, and adult reciters',
        'tajweed',
        [
            ['q' => 'Can Rochdale students keep classes during Ramadan?', 'a' => 'We shift to earlier UK evenings or weekends in Ramadan so fasting students are not reciting at their most exhausted hour unless they choose that.'],
            ['q' => 'Do you help with Quran reading if the child is weak in English phonics too?', 'a' => 'We go slowly on Arabic letters and do not pile on English reading homework. Parents should still support school phonics separately.'],
            ['q' => 'Is there a free trial in Rochdale?', 'a' => 'Yes. Book a UK-time trial and we match a tutor to the child’s current level.'],
        ],
    ]),

    rq_uk_loc(['preston', 'Preston', 'city', 'Lancashire', true,
        ['Deepdale', 'Frenchwood', 'Avenham', 'Ribbleton', 'Fishwick', 'St Matthew’s'],
        'Preston has a significant Muslim population around Deepdale and Frenchwood, with Gujarati and Pakistani families and a university that brings additional Muslim students into the city.',
        'Preston households want Quran classes that work for both settled families and students on short tenancies. Live online 1-1 teaching does not depend on finding a new local madrasa every September.',
        'University terms and family mosque times collide. A private timetable lets a Deepdale child and a UCLan student both keep a weekly recitation slot.',
        'We offer Qaida, Tajweed, Hifz, and female tutors, all on UK time.',
        'Families, university students, and sisters',
        'tajweed',
        [
            ['q' => 'Can a student who only lives in Preston during term time still enrol?', 'a' => 'Yes. Online classes continue if they go home to another UK city in the holidays, as long as they keep the same timezone and device setup.'],
            ['q' => 'Do you teach Gujarati-speaking families?', 'a' => 'Lessons are in English. Many Preston Gujarati families already use English at school; we explain rules in simple language.'],
            ['q' => 'How soon can we start after the trial?', 'a' => 'If a tutor slot fits, regular classes can start the following week.'],
        ],
    ]),

    rq_uk_loc(['huddersfield', 'Huddersfield', 'city', 'West Yorkshire', true,
        ['Thornton Lodge', 'Lockwood', 'Crosland Moor', 'Fartown', 'Birkby', 'Paddock'],
        'Huddersfield’s Muslim community is well established in Thornton Lodge, Lockwood, and Crosland Moor, with Kashmiri heritage and a strong mosque tradition.',
        'Huddersfield parents often want Hifz that is serious but humane, plus Tajweed that stops children racing through pages. Our tutors teach live, one student at a time, on UK evenings.',
        'Valley roads and winter nights make an extra trip across town unpopular. Home classes keep consistency without losing the teacher’s ear for mistakes.',
        'We set revision that older brothers and uncles can listen to, which many Kirklees families already do culturally.',
        'Hifz-age boys and girls, sisters, and adults',
        'hifz',
        [
            ['q' => 'Do Huddersfield Hifz students need to already know Tajweed?', 'a' => 'Basic reading is needed. We repair Tajweed alongside memorisation rather than waiting for perfection before the first surah.'],
            ['q' => 'Can girls in Huddersfield have a female Hifz teacher?', 'a' => 'Yes, subject to timetable. We prioritise this when families request it at enrolment.'],
            ['q' => 'Are classes suitable during GCSE years?', 'a' => 'We reduce new lesson size during exam terms and protect revision of old Juz so memorisation does not unravel.'],
        ],
    ]),

    rq_uk_loc(['derby', 'Derby', 'city', 'East Midlands', true,
        ['Normanton', 'Pear Tree', 'Rosehill', 'Osmaston', 'Littleover', 'Sunny Hill'],
        'Derby’s Pakistani and Muslim communities around Normanton and Pear Tree are long-standing, with busy mosques and a practical, working-city rhythm tied to rail and manufacturing jobs.',
        'Derby families need Quran lessons that survive shift patterns and school clubs. Rooh Ul Quran Academy books live UK-time classes so recitation is not postponed until “a quieter month”.',
        'Group madrasa cannot always correct every qalqalah. A private online tutor can stop the student, repeat the letter, and only then move on.',
        'We keep parents informed with short notes, not long reports nobody reads.',
        'Children, sisters, and factory or rail-shift parents learning later in the evening',
        'tajweed',
        [
            ['q' => 'Can a parent in Derby who works nights still take adult Tajweed?', 'a' => 'We try to place adult learners in late UK evening or weekend slots. Tell us the shift pattern at trial booking.'],
            ['q' => 'Do you teach children who already finished Qaida in a Derby mosque?', 'a' => 'Yes. We assess recitation live and start from Quran reading with Tajweed, not from page one of Qaida unless needed.'],
            ['q' => 'Is there a family discount for siblings?', 'a' => 'Ask at enrolment. Consecutive sibling slots are the most practical arrangement for Derby homes.'],
        ],
    ]),

    rq_uk_loc(['nottingham', 'Nottingham', 'city', 'East Midlands', true,
        ['Hyson Green', 'Forest Fields', 'Radford', 'Mapperley', 'Sneinton', 'The Meadows'],
        'Nottingham’s Muslim communities in Hyson Green, Forest Fields, and Radford include Pakistani, Arab, and African families, plus a large student population.',
        'Nottingham parents and students want flexible Quran classes that still feel disciplined. Live 1-1 online lessons give a Forest Fields child and a university student two different plans under the same academy.',
        'Tram times, student jobs, and school homework compete with madrasa. A home class that starts on the minute is easier to keep than a cross-city bus to an evening hall.',
        'Tutors focus on clear Tajweed, steady Hifz, and kind classroom adab on camera.',
        'Families, students, and sisters',
        'kids',
        [
            ['q' => 'Can Nottingham university students pause for summer if they leave the city?', 'a' => 'You can pause or continue from another UK address. Online delivery does not depend on remaining in NG7.'],
            ['q' => 'Do you have teachers for children with low confidence?', 'a' => 'Yes. We go slower and celebrate small wins so a shy child in Hyson Green is not compared with a faster sibling.'],
            ['q' => 'Are weekend-only plans available?', 'a' => 'They are possible, though two weekday sessions usually produce better Tajweed than one long Sunday class.'],
        ],
    ]),

    rq_uk_loc(['liverpool', 'Liverpool', 'city', 'Merseyside', true,
        ['Toxteth', 'Granby', 'Kensington', 'Wavertree', 'Anfield edge', 'City centre apartments'],
        'Liverpool’s Muslim community is smaller than Manchester’s but established, with Yemeni, Somali, and South Asian families around Toxteth and Granby, plus students across the universities.',
        'Liverpool families often cannot rely on a dense madrasa market on every street. Online 1-1 Quran classes give Toxteth children and city-centre students the same quality of tutor as larger Muslim cities.',
        'When the nearest suitable class is a long bus ride, consistency dies. Live video keeps Qaida and Tajweed in the weekly rhythm of Merseyside school life.',
        'We teach beginners through to Hifz, with female tutors and UK evening availability.',
        'Children in smaller communities, students, and new Muslims',
        'qaida',
        [
            ['q' => 'Is Liverpool too small a community for specialised female Hifz teachers locally?', 'a' => 'That is exactly why online matching helps. We can pair a Liverpool student with a qualified female tutor even if one is not available on the next street.'],
            ['q' => 'Do you teach new Muslims in Liverpool?', 'a' => 'Yes. We start with letters, pronunciation, and short surahs, without assuming mosque childhood.'],
            ['q' => 'What time do classes run?', 'a' => 'UK evenings and weekends, using Europe/London time.'],
        ],
    ]),

    rq_uk_loc(['bristol', 'Bristol', 'city', 'South West England', true,
        ['Easton', 'Lawrence Hill', 'St Pauls', 'Easton-Stapleton corridor', 'Bedminster', 'Horfield'],
        'Bristol’s Muslim community is growing around Easton and Lawrence Hill, with Somali, Pakistani, and Arab families plus professionals who moved for aerospace and tech work.',
        'Bristol parents need Quran options that match a city where mosque classes exist but fill quickly. Rooh Ul Quran Academy offers live online Tajweed and Qaida on UK time.',
        'Hilly bus routes and after-school traffic across the city make an extra trip hard. Home lessons keep children reading even in wet West Country evenings.',
        'We welcome new Muslims and children who are the only Muslim in their school year.',
        'Somali and South Asian families, professionals, and new Muslims',
        'tajweed',
        [
            ['q' => 'Can a child who is the only Muslim in a Bristol primary school still keep up?', 'a' => 'Yes. One-to-one teaching does not depend on a large peer group. We go at the child’s pace and explain why we recite, not only how.'],
            ['q' => 'Do you offer sisters-only classes?', 'a' => 'Sisters book female tutors in private 1-1 slots rather than a mixed group.'],
            ['q' => 'Are you aligned with UK school holidays?', 'a' => 'We can reduce load in August and Christmas weeks if families travel, then resume the same tutor.'],
        ],
    ]),

    rq_uk_loc(['newcastle', 'Newcastle', 'city', 'North East England', true,
        ['Elswick', 'Arthur’s Hill', 'Fenham', 'West End', 'Jesmond students', 'Gateshead-side commuters'],
        'Newcastle and the wider Tyne area have a smaller but active Muslim community in the West End, with South Asian, Arab, and student households.',
        'Newcastle families often travel further for a suitable madrasa than families in Birmingham. Online 1-1 Quran classes remove that journey while keeping a real teacher on the call.',
        'University students in Jesmond and families in Fenham need different hours. Private timetables solve that without splitting the academy’s teaching quality.',
        'We emphasise clear Tajweed for children who hear less Quran in the wider school environment of the North East.',
        'West End families, students, and adults',
        'tajweed',
        [
            ['q' => 'Is there a qualified local Hifz circle in every Newcastle neighbourhood?', 'a' => 'Not always. Online matching gives Fenham and Elswick students access to structured Hifz even when a local circle is full or distant.'],
            ['q' => 'Do classes follow UK time in winter darkness?', 'a' => 'Yes. We stay on GMT/BST. Early dusk does not change the timetable unless you ask to move earlier.'],
            ['q' => 'Can two Newcastle siblings share one login time?', 'a' => 'They should have consecutive private slots. Sharing one 30-minute call between two children is not effective.'],
        ],
    ]),

    rq_uk_loc(['cardiff', 'Cardiff', 'city', 'Wales', true,
        ['Grangetown', 'Butetown', 'Riverside', 'Cathays', 'Roath', 'Splott'],
        'Cardiff has Wales’s largest Muslim community, with Yemeni heritage in Butetown and Grangetown alongside Somali, Pakistani, and student populations in Cathays.',
        'Cardiff families want Quran teaching that respects Welsh school terms and a community that is proud, historic, and still smaller than England’s biggest Muslim cities. Live online 1-1 lessons add capacity without replacing the local mosque.',
        'Students at Cardiff universities also need Tajweed that survives essay season. A private tutor can pause and resume with the same voice.',
        'We teach Qaida, Tajweed, and Hifz, with female teachers and UK (Wales) evening hours.',
        'Grangetown families, Cathays students, and sisters',
        'qaida',
        [
            ['q' => 'Do Cardiff classes use the same timezone as England?', 'a' => 'Yes. Wales uses UK time. There is no extra conversion.'],
            ['q' => 'Can a child in Grangetown who already attends mosque still benefit?', 'a' => 'Online weekday Tajweed usually improves mosque recitation rather than competing with it.'],
            ['q' => 'Do you teach in English for mixed Yemeni and Somali households?', 'a' => 'English instruction with Arabic recitation is the default so siblings with different home languages can share the same academy method.'],
        ],
    ]),

    rq_uk_loc(['glasgow', 'Glasgow', 'city', 'Scotland', true,
        ['Pollokshields', 'Govanhill', 'Woodlands', 'Southside', 'East End', 'West End students'],
        'Glasgow has Scotland’s largest Muslim population, especially Pakistani families in Pollokshields and Govanhill, with a distinct Scottish school calendar and mosque culture.',
        'Glasgow parents need teachers who understand that Scottish term dates and darker winter afternoons are not the same as an English south-east commute. Our live classes are still booked in UK time, with slots that fit Glasgow school finishes.',
        'Southside madrasas are valued; they can still leave a child needing private Tajweed. One-to-one video lessons fill that role without another bus across the Clyde in the rain.',
        'We offer female tutors, Hifz plans that respect Highers, and beginner Qaida.',
        'Pollokshields families, sisters, and university students',
        'hifz',
        [
            ['q' => 'Do you follow the Scottish school holiday pattern?', 'a' => 'Tell us your local authority calendar at enrolment. We can ease load in October week and during exam diets.'],
            ['q' => 'Can Glasgow students take class at 4pm when it is already dark in winter?', 'a' => 'Yes. After-school UK slots remain after-school even when sunset is early.'],
            ['q' => 'Are female Hifz teachers available for sisters in Pollokshields?', 'a' => 'We prioritise female tutors when requested. Ask at the trial so we match before the first paid week.'],
        ],
    ]),

    rq_uk_loc(['edinburgh', 'Edinburgh', 'city', 'Scotland', true,
        ['Leith', 'Southside', 'Tollcross', 'Gorgie', 'Newington', 'City centre'],
        'Edinburgh’s Muslim community is smaller than Glasgow’s but includes professionals, students, and families across Leith and the Southside, with festival-season disruption unlike any other UK city.',
        'Edinburgh households need Quran classes that survive festival crowds, university terms, and a community where children may have few Muslim classmates. Live 1-1 online teaching is private, calm, and consistent.',
        'Finding a female teacher locally at the right hour is not always easy. Online matching solves that without waiting for a new mosque circle to open.',
        'Tutors keep lessons structured so festival weeks and exam diets do not erase recitation progress.',
        'Professionals, students, and families in a smaller community',
        'tajweed',
        [
            ['q' => 'Can we pause in August during Edinburgh Festival homestays?', 'a' => 'Yes. Pause and resume with the same tutor where possible so the child does not restart Qaida from scratch.'],
            ['q' => 'Do you teach children who attend non-Muslim-majority primary schools?', 'a' => 'That is common in Edinburgh. We explain basics patiently and never assume a large peer madrasa culture.'],
            ['q' => 'Is the timezone the same as London?', 'a' => 'Scotland uses UK time. Booking is in GMT/BST.'],
        ],
    ]),

    rq_uk_loc(['belfast', 'Belfast', 'city', 'Northern Ireland', true,
        ['South Belfast', 'University area', 'City centre', 'Ormeau corridor', 'Lisburn Road', 'Stranmillis'],
        'Belfast’s Muslim community is smaller than those in English mill towns, made up of professionals, students, and families who often cannot walk to a large daily madrasa.',
        'Belfast parents and students need a reliable Quran teacher more than they need another generic city landing page. Rooh Ul Quran Academy provides live 1-1 classes in UK time, including Northern Ireland evenings.',
        'When the nearest suitable class is limited, online learning is not a luxury; it is how a child keeps weekly recitation without a long evening drive.',
        'We teach Qaida, Tajweed, and Hifz with female tutor options and a free UK-time trial.',
        'Small-community families, students, and new Muslims',
        'qaida',
        [
            ['q' => 'Does Northern Ireland use the same time as England?', 'a' => 'Yes. Belfast is on UK time. We do not book you against Pakistan hours unless you ask.'],
            ['q' => 'Can a child who is one of very few Muslims in their Belfast school still join?', 'a' => 'Yes. One-to-one class is often more comfortable than being the only child in a mixed-age hall.'],
            ['q' => 'Do you support new Muslims in Belfast?', 'a' => 'We start from letters and short surahs, with clear English explanation and no assumed background.'],
        ],
    ]),

    rq_uk_loc(['tower-hamlets', 'Tower Hamlets', 'london_borough', 'East London', true,
        ['Whitechapel', 'Bethnal Green', 'Shadwell', 'Poplar', 'Bow', 'Wapping'],
        'Tower Hamlets has one of the highest Muslim population shares of any local authority in England, with a large British Bangladeshi community around Whitechapel and a dense mosque landscape.',
        'Families in Tower Hamlets often already live within walking distance of a madrasa. They still ask for private online Tajweed because group halls are noisy and teachers cannot stop for every child’s meem sakinah.',
        'After-school clubs, small flats, and shift work in hospitality make an extra evening hall difficult. A headset and a live tutor turn a Whitechapel living room into a focused recitation space.',
        'We offer female teachers, Qaida for the youngest, and Hifz plans that respect Tower Hamlets school days.',
        'Bangladeshi-heritage children, sisters, and working parents',
        'tajweed',
        [
            ['q' => 'If we already have a mosque class in Whitechapel, why add online lessons?', 'a' => 'Use mosque time for community and online time for precision. The tutor can pause your child for a full minute on one letter — a hall class cannot.'],
            ['q' => 'Do teachers understand East London school hours?', 'a' => 'We book in UK time after typical Tower Hamlets school finishes, including later slots when parents return from work.'],
            ['q' => 'Can mothers learn Tajweed while children are at school?', 'a' => 'Daytime female-tutor slots are often easier to find for sisters than peak after-school hours.'],
        ],
    ]),

    rq_uk_loc(['newham', 'Newham', 'london_borough', 'East London', true,
        ['East Ham', 'Upton Park', 'Forest Gate', 'Plaistow', 'Manor Park', 'Stratford'],
        'Newham is among London’s most Muslim boroughs, with large Pakistani, Bangladeshi, African, and Eastern European Muslim communities around East Ham, Forest Gate, and Plaistow.',
        'Newham families want Quran classes that cope with crowded housing, several siblings, and school days that already include clubs. Live 1-1 online lessons let each child have a quiet turn with a teacher.',
        'Madrasa waiting lists in East Ham are familiar. Starting or continuing Qaida online means a child does not lose a year waiting for a hall place.',
        'Tutors keep lessons practical, with female options and UK evenings.',
        'Large sibling groups, sisters, and beginners',
        'kids',
        [
            ['q' => 'Can four siblings in a Newham flat take class the same evening?', 'a' => 'Consecutive slots work if you have one quiet corner. We will not put four children on one call together.'],
            ['q' => 'Do you teach children who switch between mosque and online in Forest Gate?', 'a' => 'Yes. Tell us the mosque homework so we reinforce rather than confuse.'],
            ['q' => 'Are classes after Stratford after-school clubs possible?', 'a' => 'Later UK evenings are available. Book the trial for the hour you can actually keep each week.'],
        ],
    ]),

    rq_uk_loc(['redbridge', 'Redbridge', 'london_borough', 'East London', true,
        ['Ilford', 'Loxford', 'Goodmayes', 'Seven Kings', 'Barkingside', 'Gants Hill'],
        'Redbridge, especially Ilford and Loxford, has a large Muslim population with Pakistani, Indian, and Bangladeshi families and a strong private-tuition culture alongside mosque classes.',
        'Redbridge parents often already pay for school tutoring. They want Quran teaching that is equally structured: punctual, one-to-one, and measurable. Our online academy is built that way.',
        'Children can be over-scheduled between 11-plus prep and madrasa. We keep Quran slots realistic so recitation is not the first thing dropped in Year 6.',
        'Female tutors, Hifz, and Tajweed repair are all available on UK time.',
        'School-driven families, sisters, and Hifz students',
        'hifz',
        [
            ['q' => 'Can we reduce Hifz load during 11-plus season in Ilford?', 'a' => 'Yes. Protect revision of old lessons and shrink new sabaq until exams pass.'],
            ['q' => 'Do you teach both boys and girls in Redbridge households?', 'a' => 'Yes. Girls can request a female teacher. Boys are paired with male teachers where families prefer that.'],
            ['q' => 'Is Ilford on London time?', 'a' => 'Redbridge uses UK time like the rest of London.'],
        ],
    ]),

    rq_uk_loc(['waltham-forest', 'Waltham Forest', 'london_borough', 'East London', false,
        ['Walthamstow', 'Leyton', 'Leytonstone', 'Chingford', 'Higham Hill', 'Markhouse'],
        'Waltham Forest’s Muslim communities in Walthamstow and Leyton include Pakistani, Turkish, Somali, and Eastern European families, with a younger borough feel than inner East London.',
        'Waltham Forest parents need Quran classes that survive Overground commutes and after-school football. Live online Tajweed starts when the child is actually home, not when a hall timetable dictates.',
        'Flats can be noisy. We still prefer a headset and a corner with the door closed over skipping class entirely.',
        'Qaida, Tajweed, and Hifz are offered with female tutors on UK evenings.',
        'Primary children, sisters, and working parents',
        'tajweed',
        [
            ['q' => 'Can Leyton children join immediately after coming off the Overground?', 'a' => 'Build a 15-minute buffer into the booking so the child is seated, not reciting while still in a coat.'],
            ['q' => 'Do you teach Turkish-heritage as well as Pakistani-heritage children?', 'a' => 'Yes. Instruction is in English. Recitation standards are the same.'],
            ['q' => 'Are weekend classes available in Walthamstow?', 'a' => 'Saturday and Sunday UK slots exist, though weekday consistency is better for Tajweed.'],
        ],
    ]),

    rq_uk_loc(['barking-and-dagenham', 'Barking and Dagenham', 'london_borough', 'East London', false,
        ['Barking', 'Dagenham', 'Becontree', 'Thames View', 'Chadwell Heath', 'Goresbrook'],
        'Barking and Dagenham has seen rapid growth in Muslim households, with families moving from inner East London for housing while still commuting toward Whitechapel and Ilford for work and mosque ties.',
        'Parents here often need a Quran plan that does not assume they still live next to last year’s madrasa. Online 1-1 classes stay with the child even if the family moved from Newham to Becontree.',
        'Longer school-run distances in the borough make an extra evening hall costly in time. Home recitation with a live tutor protects progress.',
        'We offer beginners’ Qaida through Hifz, female teachers, and UK-time booking.',
        'Recently moved families, siblings, and sisters',
        'qaida',
        [
            ['q' => 'We moved from Newham to Dagenham. Can the same online teacher continue?', 'a' => 'Yes. That continuity is a main reason families in this borough choose live online classes.'],
            ['q' => 'Do you teach children who now have a longer commute to their old mosque?', 'a' => 'Weekday online lessons reduce the need for a midweek mosque trip while weekend jumu’ah can stay as it is.'],
            ['q' => 'Are after-school slots available?', 'a' => 'UK after-school and later evening slots are the standard offer.'],
        ],
    ]),

    rq_uk_loc(['brent', 'Brent', 'london_borough', 'North West London', true,
        ['Wembley', 'Alperton', 'Kingsbury', 'Neasden', 'Queen’s Park', 'Harlesden'],
        'Brent, especially Wembley and Kingsbury, has a large and diverse Muslim population including Indian, Pakistani, Somali, and Arab families living alongside one of London’s busiest event and commuting belts.',
        'Brent parents need Quran classes that survive stadium event traffic and late returns from central London jobs. A live online tutor waits in the diary, not at a hall that cannot start late.',
        'Children may already attend weekend madrasa in Wembley. Weekday Tajweed online is how recitation stays sharp between Saturdays.',
        'Female tutors and Hifz plans are available on UK time.',
        'Wembley families, sisters, and commuter households',
        'tajweed',
        [
            ['q' => 'What happens to class on a Wembley Stadium event night?', 'a' => 'Because the class is at home, stadium traffic does not cancel recitation. If the household itself is hosting guests, we can reschedule within the week.'],
            ['q' => 'Do you teach Gujarati and Urdu-speaking families in Kingsbury?', 'a' => 'English is the classroom language. Recitation is in Arabic. Parents can still sit in on the trial.'],
            ['q' => 'Can adults in Alperton learn after 9pm?', 'a' => 'Late UK slots are limited but often possible for adults. Ask at booking.'],
        ],
    ]),

    rq_uk_loc(['ealing', 'Ealing', 'london_borough', 'West London', false,
        ['Southall', 'Greenford', 'Hanwell', 'West Ealing', 'Acton', 'Northolt'],
        'Ealing’s Muslim communities, particularly Southall and Greenford, include large Pakistani, Afghan, and Somali populations as well as West London professionals.',
        'Ealing families want Quran teaching that copes with Piccadilly and Elizabeth line commutes and with Southall’s dense mosque culture. Online 1-1 lessons add a private Tajweed hour without another minibus.',
        'Afghan and Pakistani households sometimes want different starting points. A private tutor begins from the child’s actual recitation, not a one-size borough syllabus.',
        'We provide female teachers, Qaida, and Hifz on UK evenings.',
        'Southall families, Afghan households, and sisters',
        'qaida',
        [
            ['q' => 'Can a child in Southall who already reads fluently still need Tajweed class?', 'a' => 'Fluency without rules is common. We slow the recitation and rebuild noon sakinah, madd, and makharij.'],
            ['q' => 'Do you have female tutors for sisters in Greenford?', 'a' => 'Yes. Request this on the trial form.'],
            ['q' => 'Are classes suitable during West London rush hour?', 'a' => 'Book after the commute, not during it. The child should be home and seated.'],
        ],
    ]),

    rq_uk_loc(['hounslow', 'Hounslow', 'london_borough', 'West London', false,
        ['Hounslow Central', 'Heston', 'Cranford', 'Isleworth', 'Feltham', 'Osterley'],
        'Hounslow has a large Muslim population linked to Heathrow employment, with Pakistani, Indian, and Afghan families around Heston, Cranford, and Hounslow town.',
        'Hounslow parents on airport shifts cannot promise the same evening every week unless the Quran class can move. Live online teaching is easier to retarget than a fixed mosque hall.',
        'Children still need a repeating weekly backbone. We aim for two predictable UK slots and use weekends when a shift pattern explodes.',
        'Qaida, Tajweed, Hifz, and female tutors are available.',
        'Airport-shift families, sisters, and school children',
        'tajweed',
        [
            ['q' => 'Can Hounslow shift workers change class time month to month?', 'a' => 'We try to keep the same tutor and move the slot when the roster changes. Give us as much notice as the airport gives you.'],
            ['q' => 'Do you teach children who miss madrasa because of parent overtime?', 'a' => 'That is a common Hounslow story. Online class at home is designed for those weeks.'],
            ['q' => 'Is Heathrow noise a problem on the call?', 'a' => 'A headset and a room away from the main road helps. We will pause rather than mark a letter we cannot hear.'],
        ],
    ]),

    rq_uk_loc(['harrow', 'Harrow', 'london_borough', 'North West London', false,
        ['Wealdstone', 'Harrow Town', 'Kenton', 'Queensbury', 'Stanmore', 'Rayners Lane'],
        'Harrow has a substantial Muslim community, including Indian, Pakistani, and Somali families in Wealdstone, Kenton, and Queensbury, with a strong culture of academic tutoring.',
        'Harrow parents treat Quran as seriously as school. They want punctual online lessons, visible homework, and a teacher who will not inflate Hifz speed to impress.',
        'Children may already have weekday tutors for maths. We place Quran in a realistic gap, often early evening, so the week is demanding but not chaotic.',
        'Female tutors and structured Hifz are available on UK time.',
        'Academically busy children, sisters, and adults',
        'hifz',
        [
            ['q' => 'Can Harrow students do Hifz alongside grammar-school homework?', 'a' => 'Yes, with a smaller new lesson and protected revision. We will say no to unsafe speed.'],
            ['q' => 'Do you offer female teachers in Wealdstone?', 'a' => 'Yes, for girls and mothers.'],
            ['q' => 'What if a weekday slot clashes with school club?', 'a' => 'Move to another UK evening or a weekend with the same tutor rather than skipping twice a month.'],
        ],
    ]),

    rq_uk_loc(['enfield', 'Enfield', 'london_borough', 'North London', false,
        ['Edmonton', 'Ponders End', 'Enfield Town', 'Palmers Green', 'Southgate', 'Bush Hill Park'],
        'Enfield’s Muslim communities in Edmonton and Ponders End include Turkish, Kurdish, Somali, and Pakistani families, with a North London mix of suburban streets and busy high roads.',
        'Enfield parents want Quran classes that work when the child has a long school journey up the borough. Online 1-1 teaching starts at home, which matters more here than in a compact inner-city ward.',
        'Turkish and Kurdish households may have different mosque habits from South Asian neighbours. A private tutor starts from the student in front of the camera.',
        'We offer Qaida, Tajweed, Hifz, and female tutors on UK evenings.',
        'Edmonton families, Turkish-heritage children, and sisters',
        'qaida',
        [
            ['q' => 'Do you teach Turkish-speaking children in Edmonton?', 'a' => 'Classroom language is English. Recitation is Arabic. We do not require the child to know Urdu or Turkish to start Qaida.'],
            ['q' => 'Can classes start later because of long Enfield school runs?', 'a' => 'Later UK evenings are often better than 4pm slots in this borough. Book the hour you can keep.'],
            ['q' => 'Are sisters-only tutors available?', 'a' => 'Female 1-1 tutors can be requested at trial.'],
        ],
    ]),
];
