<?php

/**
 * Locations 36–100. Merged by tools/generate-uk-locations.php
 */

return [

    rq_uk_loc(['dewsbury', 'Dewsbury', 'city', 'West Yorkshire', false,
        ['Savile Town', 'Thornhill Lees', 'Westtown', 'Earlsheaton', 'Dewsbury Moor', 'Batley Carr'],
        'Dewsbury, especially Savile Town, is one of the most concentrated Muslim towns in Britain, with Kashmiri families and a dense mosque and madrasa culture.',
        'Dewsbury parents usually already have access to local Quran teaching. They use Rooh Ul Quran Academy when they want private Tajweed, a female teacher, or a Hifz plan that does not depend on a packed hall.',
        'Even in a town with many mosques, one-to-one time is scarce. Live online lessons give each child an undivided tutor on UK evenings.',
        'We respect existing madrasa homework and use online minutes for precision and revision.',
        'Hifz students, sisters, and children who need slower Tajweed',
        'hifz',
        [
            ['q' => 'Why would a Dewsbury family need online classes if mosques are nearby?', 'a' => 'Proximity is not the same as private correction. A hall cannot stop for every child’s qalqalah. Online 1-1 can.'],
            ['q' => 'Can we keep our Savile Town madrasa and add you on weekdays?', 'a' => 'That is the most common pattern. Tell us the madrasa sabaq so we do not clash.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes, for girls and mothers who prefer to learn at home.'],
        ],
    ]),

    rq_uk_loc(['batley', 'Batley', 'city', 'West Yorkshire', false,
        ['Batley Carr', 'Staincliffe', 'Mount Pleasant', 'Hanging Heaton', 'Soothill', 'Carlinghow'],
        'Batley sits in the heavy-wool towns of Kirklees with a large Kashmiri Muslim community and close ties to neighbouring Dewsbury.',
        'Batley families want Quran classes that fit mill-town work hours and school nights without a drive to a larger hall. Live online 1-1 teaching keeps recitation in the home.',
        'Siblings often share devices. Consecutive private slots work better than one chaotic group call.',
        'Tutors emphasise adab, slow reading, and parent-visible revision lists.',
        'Primary children, Hifz hopefuls, and sisters',
        'qaida',
        [
            ['q' => 'Can Batley and Dewsbury cousins share similar timetable patterns?', 'a' => 'Yes. Both towns use UK evenings. Each child still needs their own tutor slot.'],
            ['q' => 'Do you teach children who already recite fast but unclearly?', 'a' => 'We slow them down first. Speed without makharij is not progress.'],
            ['q' => 'Is a free trial available?', 'a' => 'Yes, booked in UK time.'],
        ],
    ]),

    rq_uk_loc(['keighley', 'Keighley', 'city', 'West Yorkshire', false,
        ['Showfield', 'Lund Park', 'Eastwood', 'Utley', 'Knowle Park', 'Stockbridge'],
        'Keighley has a well-known Pakistani-heritage Muslim community in Airedale, with mosque life that is central to many households.',
        'Keighley parents need consistent Quran teaching through wet valley winters and after-school tiredness. Online live classes remove the extra evening journey while keeping a real teacher.',
        'Local madrasas are valued. Private Tajweed online is extra precision, not a replacement for community.',
        'We offer Hifz structure, female tutors, and UK-time booking.',
        'School children, sisters, and adults',
        'tajweed',
        [
            ['q' => 'Can Keighley students join from a phone after football practice?', 'a' => 'Give them ten minutes to sit down. Reciting while still breathless wastes the tutor’s ear for mistakes.'],
            ['q' => 'Do you follow Yorkshire school holidays?', 'a' => 'Tell us Bradford/Kirklees dates. We can ease August and Christmas weeks.'],
            ['q' => 'Are Hifz plans realistic for town schools?', 'a' => 'We will not promise a full Quran on an unsafe timetable. Daily revision comes first.'],
        ],
    ]),

    rq_uk_loc(['halifax', 'Halifax', 'city', 'West Yorkshire', false,
        ['Stoney Royd', 'Akroydon', 'Ovenden', 'Park Ward', 'King Cross', 'Pellon'],
        'Halifax has a significant Muslim community in Calderdale, smaller than Bradford but with established Pakistani families and busy local mosques.',
        'Halifax households often travel toward Bradford for specialist classes. Online 1-1 Quran lessons keep the teacher in the child’s week without the A58 evening drive.',
        'Hills and winter weather make attendance fragile. Home recitation with a live tutor is more reliable.',
        'Qaida, Tajweed, and Hifz are taught with female tutor options.',
        'Families who would otherwise skip midweek madrasa, sisters, and beginners',
        'qaida',
        [
            ['q' => 'Is Halifax too small for a dedicated female Hifz teacher locally?', 'a' => 'Online matching is useful precisely when a specialist local slot is full or distant.'],
            ['q' => 'Can we book after Calderdale school hours?', 'a' => 'UK after-school and later evenings are standard.'],
            ['q' => 'Do grandparents need to understand the app?', 'a' => 'A parent should start the call. Grandparents can listen without managing the software.'],
        ],
    ]),

    rq_uk_loc(['burnley', 'Burnley', 'city', 'Lancashire', false,
        ['Daneshouse', 'Stoneyholme', 'Burnley Wood', 'Duke Bar', 'Queensgate', 'Gannow'],
        'Burnley has a concentrated Pakistani Muslim community around Daneshouse and Stoneyholme, with a mill-town rhythm of early evenings and strong mosque ties.',
        'Burnley parents want Quran teaching that is serious about Tajweed without requiring another walk across town after dark. Live online 1-1 classes provide that.',
        'Group madrasa can leave a quieter child uncorrected. A private tutor hears every letter.',
        'We keep UK evenings, female tutors, and clear weekly homework.',
        'Primary children, Hifz students, and sisters',
        'tajweed',
        [
            ['q' => 'Can Burnley children take class in winter when it is dark by 4:30?', 'a' => 'Yes. Darkness does not change UK after-school booking. The child learns at home.'],
            ['q' => 'Do you teach Hifz alongside Lancashire school homework?', 'a' => 'New lesson size follows how solid revision is, especially in SATS and GCSE terms.'],
            ['q' => 'Are consecutive sibling slots possible?', 'a' => 'Yes, and they are the most practical for one family device.'],
        ],
    ]),

    rq_uk_loc(['nelson', 'Nelson', 'city', 'Lancashire', false,
        ['Whitefield', 'Bradley', 'Clover Hill', 'Marsden', 'Walverden', 'Southfield'],
        'Nelson in Pendle has one of the highest Muslim population shares of any town in England, with Kashmiri families and a tightly knit mosque culture.',
        'Nelson families are surrounded by community recitation. They still benefit from a private tutor who can slow a child down and rebuild rules the hall skipped.',
        'Online classes are an addition for precision and for sisters who prefer a female teacher at home.',
        'We teach Qaida through Hifz on UK time.',
        'Children in dense community settings, sisters, and Hifz students',
        'hifz',
        [
            ['q' => 'If Nelson already has many madrasas, is online redundant?', 'a' => 'Use us for 1-1 Tajweed and Hifz tracking. Keep mosque for community. They solve different problems.'],
            ['q' => 'Can girls have female teachers?', 'a' => 'Yes. Request this at trial.'],
            ['q' => 'Do you set daily sabaq?', 'a' => 'Hifz students receive a daily new-lesson and revision map after each class.'],
        ],
    ]),

    rq_uk_loc(['accrington', 'Accrington', 'city', 'Lancashire', false,
        ['Spring Hill', 'Scaitcliffe', 'Hillock Vale', 'Milnshaw', 'Barnfield', 'Church nearby'],
        'Accrington and Hyndburn have a substantial Pakistani Muslim community, smaller than Blackburn but with the same need for consistent after-school recitation.',
        'Accrington parents often look toward Blackburn for extra classes. Online 1-1 teaching keeps a qualified tutor in the child’s week without the drive.',
        'We focus on Qaida foundations and Tajweed that does not rush.',
        'Female tutors and UK evenings are available.',
        'Primary children, sisters, and adults repairing recitation',
        'qaida',
        [
            ['q' => 'Can an Accrington child keep the same teacher if we later move to Blackburn?', 'a' => 'Yes. Online continuity is one reason mill-town families enrol.'],
            ['q' => 'Are classes in UK time?', 'a' => 'Always, unless you explicitly request another zone.'],
            ['q' => 'Do you teach adults who lead taraweeh locally?', 'a' => 'Adult Tajweed and fluency work is available in evening slots.'],
        ],
    ]),

    rq_uk_loc(['peterborough', 'Peterborough', 'city', 'Cambridgeshire', false,
        ['Millfield', 'New England', 'Central', 'Eastfield', 'Dogsthorpe', 'Ravensthorpe'],
        'Peterborough has a large and diverse Muslim population, including Pakistani, Afghan, and Eastern European Muslim families around Millfield and New England.',
        'Peterborough parents need Quran classes that work for mixed language homes and for children who may be new to English school as well as Arabic letters. Live 1-1 teaching goes at that child’s pace.',
        'The city’s growth means mosque classes can be crowded. Online lessons add a quiet recitation hour.',
        'We offer Qaida, Tajweed, Hifz, and female tutors on UK time.',
        'Newcomer families, Afghan households, and school children',
        'kids',
        [
            ['q' => 'Can a child who is still new to English start Qaida?', 'a' => 'Yes. We use demonstration, repetition, and simple English. We do not wait for perfect school English first.'],
            ['q' => 'Do you teach Afghan families in Millfield?', 'a' => 'Yes. Recitation standards are the same. Explanation is in clear English.'],
            ['q' => 'Are after-school slots available after long school runs?', 'a' => 'Book a later UK evening if 4pm is a rush. Consistency beats an early slot you always miss.'],
        ],
    ]),

    rq_uk_loc(['bedford', 'Bedford', 'city', 'Bedfordshire', false,
        ['Queens Park', 'Cauldwell', 'Castle', 'Kingsbrook', 'Greyfriars', 'Great Denham'],
        'Bedford has a long-established Muslim community, including Pakistani and Italian-heritage networks unusual in the UK, with Queens Park as a well-known centre.',
        'Bedford families want Quran teaching that sits beside county school hours and London-commuter returns. Live online 1-1 classes start when the household is actually together.',
        'Children may already attend weekend mosque. Weekday Tajweed online stops the six-day gap from undoing Saturday’s work.',
        'Female tutors and beginner Qaida are available.',
        'Commuter families, sisters, and primary children',
        'tajweed',
        [
            ['q' => 'Can parents who commute into London still supervise class?', 'a' => 'Book after they return, or let a responsible older sibling start the call with a parent check-in at the end.'],
            ['q' => 'Do you teach in Queens Park households with several children?', 'a' => 'Consecutive private slots work. One shared call does not.'],
            ['q' => 'Is Bedford on UK time like Luton?', 'a' => 'Yes. Same timezone, different local school-run pattern.'],
        ],
    ]),

    rq_uk_loc(['oxford', 'Oxford', 'city', 'Oxfordshire', false,
        ['Cowley', 'East Oxford', 'Headington', 'Jericho', 'Blackbird Leys', 'City centre'],
        'Oxford’s Muslim community mixes long-settled families in Cowley and East Oxford with a large student and academic population that changes every October.',
        'Oxford needs two kinds of Quran class: steady after-school Qaida for families, and flexible Tajweed for students who disappear into libraries at deadline. Live 1-1 online teaching can do both.',
        'Finding a female teacher at the right hour is not always easy in a smaller city community. Online matching helps.',
        'We teach beginners through Hifz on UK time, including term-time pauses.',
        'Cowley families, university students, and new Muslims in college',
        'tajweed',
        [
            ['q' => 'Can Oxford students pause for collections and resume the same tutor?', 'a' => 'Yes. Tell us exam weeks in advance. We shrink or pause rather than pile guilt onto a disappearing student.'],
            ['q' => 'Do you teach children in Cowley who already attend mosque?', 'a' => 'Weekday online Tajweed is designed to support weekend mosque, not replace it.'],
            ['q' => 'Are new Muslims in college welcome?', 'a' => 'Yes. We start from letters and short surahs with adult pacing, not a child madrasa tone.'],
        ],
    ]),

    rq_uk_loc(['milton-keynes', 'Milton Keynes', 'city', 'Buckinghamshire', false,
        ['Bletchley', 'Wolverton', 'Central MK', 'Fishermead', 'Conniburrow', 'Newport Pagnell edge'],
        'Milton Keynes has a growing Muslim population spread across a designed city of long grid drives, with families who often moved from London boroughs for housing.',
        'MK parents discover that the next mosque class can be a twenty-minute drive, not a walk. Online 1-1 Quran lessons restore consistency after that move from Brent or Newham.',
        'Children keep the same tutor even if the family later changes grid square.',
        'Qaida, Tajweed, Hifz, and female tutors run on UK evenings.',
        'London-mover families, sisters, and children in spread-out estates',
        'kids',
        [
            ['q' => 'We left London for Milton Keynes. Can online classes replace the old madrasa immediately?', 'a' => 'They can cover weekday recitation from week one. You can still join a local mosque at weekend once you find one that fits.'],
            ['q' => 'Are drives across MK a reason children drop Quran?', 'a' => 'Often yes. Home live class removes that friction.'],
            ['q' => 'Do you teach mixed Pakistani and African families in Bletchley?', 'a' => 'Yes. English instruction, Arabic recitation, child’s actual level.'],
        ],
    ]),

    rq_uk_loc(['northampton', 'Northampton', 'city', 'Northamptonshire', false,
        ['Abington', 'Semilong', 'Far Cotton', 'Kingsthorpe', 'Eastfield', 'St James'],
        'Northampton has a growing Muslim community of South Asian, African, and Eastern European families, with fewer street-level madrasas than the mill towns.',
        'Northampton parents need a dependable Quran teacher more than a huge local market. Live online 1-1 classes provide that on UK evenings.',
        'When the suitable mosque class is full, waiting a term costs recitation momentum. Online Qaida can start after a free trial.',
        'Female tutors and Hifz structure are available.',
        'Growing-community families, sisters, and beginners',
        'qaida',
        [
            ['q' => 'Is Northampton too small for specialist Hifz locally?', 'a' => 'Specialist slots can be limited. Online matching gives a structured Hifz teacher without a long waitlist.'],
            ['q' => 'Can we start a child who has not yet finished English phonics?', 'a' => 'Qaida can run in parallel. We keep Arabic letter work visual and repetitive.'],
            ['q' => 'Are UK after-school times used?', 'a' => 'Yes. Europe/London timezone.'],
        ],
    ]),

    rq_uk_loc(['reading', 'Reading', 'city', 'Berkshire', false,
        ['Oxford Road', 'Coley', 'Whitley', 'Caversham', 'Tilehurst', 'Wokingham Road'],
        'Reading has a sizeable Muslim community along the Oxford Road corridor, with Pakistani, Afghan, and professional households tied to Thames Valley employment.',
        'Reading parents juggle rail commutes into London and need Quran classes that start after the Elizabeth line / Great Western return. Live online teaching waits at home.',
        'Students at the university also need Tajweed that survives exam term. A private tutor can flex.',
        'We offer female teachers, Qaida, and Hifz on UK time.',
        'Commuter families, Afghan households, and students',
        'tajweed',
        [
            ['q' => 'Can we book after the London commute into Reading?', 'a' => 'Later UK evenings are often more realistic than 5pm. Choose the hour you keep.'],
            ['q' => 'Do you teach university students in term time only?', 'a' => 'Students can pause for holidays or continue from their hometown on the same UK timezone.'],
            ['q' => 'Are female tutors available for sisters in Coley?', 'a' => 'Yes. Request at trial.'],
        ],
    ]),

    rq_uk_loc(['high-wycombe', 'High Wycombe', 'city', 'Buckinghamshire', false,
        ['Sands', 'Terriers', 'Micklefield', 'Cressex', 'Totteridge', 'Downley'],
        'High Wycombe has a well-known Pakistani Muslim community, with mosque life that is central for many families in the Chilterns commuter belt.',
        'Wycombe parents often already have weekend madrasa. They come to us for weekday Tajweed and for female 1-1 teaching that a busy hall cannot offer every child.',
        'A40 and M40 commutes wreck fixed 5pm plans. Book the slot after the household is home.',
        'Hifz and Qaida run live online in UK time.',
        'Settled Pakistani families, sisters, and school children',
        'hifz',
        [
            ['q' => 'Can High Wycombe children keep mosque on Saturday and online on Tuesday/Thursday?', 'a' => 'That split is ideal. Share mosque homework so we reinforce it.'],
            ['q' => 'Do you slow down children who race recitation?', 'a' => 'Yes. Racing is one of the first habits we break in 1-1 Tajweed.'],
            ['q' => 'Are late slots possible after M40 returns?', 'a' => 'Ask for later UK evenings if 5pm always slips.'],
        ],
    ]),

    rq_uk_loc(['watford', 'Watford', 'city', 'Hertfordshire', false,
        ['Central Watford', 'North Watford', 'Holywell', 'Oxhey', 'Garston', 'Bushey edge'],
        'Watford has a diverse Muslim community of commuters, long-settled families, and newcomers using the London Underground Metropolitan line pattern of life.',
        'Watford parents need Quran classes that survive Met Line delays. A live online tutor at home is more reliable than a hall that cannot wait.',
        'Children may attend London-edge mosques at weekends. Weekday online Tajweed fills the gap.',
        'Female tutors, Qaida, and Hifz are available on UK time.',
        'Commuter families, sisters, and beginners',
        'kids',
        [
            ['q' => 'If the Metropolitan line is delayed, can class start ten minutes late?', 'a' => 'Message the tutor. A one-off delay is better than cancelling. Repeated lateness should move the booking later.'],
            ['q' => 'Do you teach mixed Gujarati and Somali households in Watford?', 'a' => 'English classroom language, Arabic recitation, individual starting point.'],
            ['q' => 'Is a free trial on UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['croydon', 'Croydon', 'london_borough', 'South London', false,
        ['West Croydon', 'Thornton Heath', 'Norbury', 'South Croydon', 'Addiscombe', 'Broad Green'],
        'Croydon has a large and growing Muslim population in south London, including Pakistani, Afghan, and African families around Thornton Heath and West Croydon.',
        'Croydon school runs and tram times eat the evening. Online 1-1 Quran classes start when the child is home in Thornton Heath, not when a north-London hall timetable says so.',
        'The borough is huge; a suitable female teacher may not be on the next street. Online matching solves that.',
        'We teach Qaida, Tajweed, and Hifz on UK evenings.',
        'Thornton Heath families, sisters, and after-school children',
        'tajweed',
        [
            ['q' => 'Can Thornton Heath children join after tram clubs?', 'a' => 'Book a later slot with a buffer. Do not start while still on the tram.'],
            ['q' => 'Do you have female tutors for sisters in Croydon?', 'a' => 'Yes. Request this when you book the trial.'],
            ['q' => 'Is Croydon treated as a London page for search?', 'a' => 'This landing uses the London URL pattern because Croydon is a London borough, with copy specific to south London life.'],
        ],
    ]),

    rq_uk_loc(['hackney', 'Hackney', 'london_borough', 'East London', false,
        ['Stoke Newington', 'Dalston', 'Clapton', 'Homerton', 'Shacklewell', 'London Fields'],
        'Hackney’s Muslim communities include Turkish, Kurdish, Somali, and South Asian families alongside a rapidly changing inner-London housing mix.',
        'Hackney parents need Quran classes that work in smaller flats and with late school finishes. A headset and a live tutor beat a crowded hall for Tajweed precision.',
        'Turkish and Somali households should not be forced into one assumed madrasa background. Private teaching starts from the child on camera.',
        'Female tutors and UK evenings are standard options.',
        'Turkish-heritage children, Somali families, and sisters',
        'qaida',
        [
            ['q' => 'Do you assume every Hackney child already attends madrasa?', 'a' => 'No. Many start Qaida with us because local groups are full or not the right fit.'],
            ['q' => 'Can classes work in a small flat?', 'a' => 'Yes, if you can find a relatively quiet corner and a headset.'],
            ['q' => 'Are after-school UK slots available?', 'a' => 'Yes, including later evenings for working parents in the borough.'],
        ],
    ]),

    rq_uk_loc(['camden', 'Camden', 'london_borough', 'Central London', false,
        ['Regent’s Park edge', 'Somers Town', 'Kentish Town', 'Gospel Oak', 'Kilburn border', 'Bloomsbury students'],
        'Camden’s Muslim community includes long-settled Somali and Bangladeshi families in Somers Town as well as students and professionals around Bloomsbury.',
        'Camden life is noisy, central, and time-poor. Live online Quran classes let a Somers Town child and a UCL student both keep a private recitation slot without crossing the borough.',
        'Festival-like busyness around central London is not an excuse to drop Tajweed if the class is at home.',
        'We offer female tutors, adult Tajweed, and children’s Qaida on UK time.',
        'Somers Town families, students, and professionals',
        'tajweed',
        [
            ['q' => 'Can Bloomsbury students book around lecture hours?', 'a' => 'Yes. Tell us the timetable. We prefer two shorter weekly slots over one that always collides with seminars.'],
            ['q' => 'Do Somers Town children need to travel to Whitechapel for quality teaching?', 'a' => 'Not for weekday 1-1 Tajweed. Online brings the tutor to the home.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['westminster', 'Westminster', 'london_borough', 'Central London', false,
        ['Edgware Road', 'Marylebone', 'Paddington', 'Bayswater', 'Church Street', 'Pimlico'],
        'Westminster includes the Edgware Road corridor, one of London’s best-known Arab and Muslim high streets, plus Paddington families and a large visitor and professional mix.',
        'Westminster households may hear Quran in shops and mosques daily and still lack a private teacher who will correct their child’s meem sakinah. Live 1-1 online lessons provide that focus.',
        'Shift work in hospitality around the West End wrecks hall timetables. Home classes can sit in the actual gap in the roster.',
        'Arabic-speaking and English-speaking families are both welcome; recitation rules are the same.',
        'Edgware Road families, hospitality-shift parents, and sisters',
        'tajweed',
        [
            ['q' => 'Do you teach children who already speak Arabic at home?', 'a' => 'Yes. Arabic home language does not automatically mean correct Tajweed. We still drill makharij.'],
            ['q' => 'Can Paddington hospitality staff take late classes?', 'a' => 'Late UK slots are limited. Ask — adults are often easier to place after 9pm than children.'],
            ['q' => 'Is the URL a London borough page?', 'a' => 'Yes. Westminster uses the London path pattern with unique central-London copy.'],
        ],
    ]),

    rq_uk_loc(['southwark', 'Southwark', 'london_borough', 'South London', false,
        ['Peckham', 'Walworth', 'Bermondsey', 'Elephant and Castle', 'Camberwell', 'Rotherhithe'],
        'Southwark’s Muslim communities in Peckham, Walworth, and the Elephant include African, Caribbean-heritage Muslim, and South Asian families in a densely built inner-south borough.',
        'Southwark parents want Quran classes that work after long primary days and in homes where space is tight. Live 1-1 online teaching is private and portable across temporary housing moves within the borough.',
        'A suitable sisters’ circle may not exist on the next estate. Online female tutors fill that gap.',
        'Qaida and Tajweed on UK evenings are the core offer.',
        'Peckham families, sisters, and children in temporary housing',
        'kids',
        [
            ['q' => 'If we move from Walworth to Peckham, does the teacher change?', 'a' => 'No. The same online tutor continues, which matters when housing moves mid-year.'],
            ['q' => 'Do you teach African as well as South Asian families?', 'a' => 'Yes. We do not assume one community’s madrasa background.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes, on request.'],
        ],
    ]),

    rq_uk_loc(['lambeth', 'Lambeth', 'london_borough', 'South London', false,
        ['Brixton', 'Stockwell', 'Streatham', 'Clapham', 'Gipsy Hill', 'Kennington'],
        'Lambeth’s Muslim communities around Brixton, Stockwell, and Streatham include Somali, Portuguese-speaking, and South Asian families in a busy inner-south London borough.',
        'Lambeth school and mosque options exist but fill. Online 1-1 Quran classes give a Streatham child a dedicated recitation hour without a bus to another borough.',
        'We teach calmly, which helps children who find large halls overwhelming.',
        'Female tutors and UK evenings are available.',
        'Somali families, sisters, and primary children',
        'qaida',
        [
            ['q' => 'Can a shy child in Brixton learn better 1-1 than in a hall?', 'a' => 'Often yes. Private video class removes the fear of reciting in front of a row of peers.'],
            ['q' => 'Do you teach Somali-heritage children starting Qaida?', 'a' => 'Yes. English explanation, Arabic letters, child’s pace.'],
            ['q' => 'Are weekend slots available in Streatham?', 'a' => 'Yes, though two weekdays usually beat one long Sunday session.'],
        ],
    ]),

    rq_uk_loc(['greenwich', 'Greenwich', 'london_borough', 'South East London', false,
        ['Woolwich', 'Plumstead', 'Thamesmead', 'Greenwich Town', 'Charlton', 'Abbey Wood'],
        'Greenwich borough’s Muslim population is especially visible in Woolwich and Plumstead, with South Asian, African, and Nepali-linked households and long DLR/Elizabeth line commutes.',
        'Woolwich families need Quran classes that survive river-crossing commutes. Online 1-1 lessons start at home in Plumstead rather than depending on a hall on the other side of the Thames.',
        'New builds in Thamesmead often lack a walkable madrasa. Live video fills that gap from week one.',
        'Qaida, Tajweed, Hifz, and female tutors run on UK time.',
        'Woolwich families, Thamesmead newcomers, and sisters',
        'tajweed',
        [
            ['q' => 'We moved into a new Thamesmead flat with no nearby madrasa. Can we start immediately?', 'a' => 'Yes. After a UK-time trial we can begin regular Qaida or Tajweed the following week if a slot exists.'],
            ['q' => 'Do Woolwich mosque students still benefit?', 'a' => 'Weekday online precision usually improves weekend mosque recitation.'],
            ['q' => 'Are later evenings available after Abbey Wood commutes?', 'a' => 'Yes. Book the hour you can keep, not the earliest listed time.'],
        ],
    ]),

    rq_uk_loc(['lewisham', 'Lewisham', 'london_borough', 'South East London', false,
        ['Catford', 'Lewisham Town', 'Deptford', 'New Cross', 'Downham', 'Brockley'],
        'Lewisham has a diverse Muslim community across Deptford, Catford, and Lewisham town, including African, Turkish, and South Asian families.',
        'Lewisham parents juggle Overground and DLR connections. A Quran class that lives on a bus timetable fails; a class that lives on the home wifi can hold.',
        'We teach 1-1 so a quieter child in Catford is not skipped in a mixed-age hall.',
        'Female tutors and beginner Qaida are available on UK evenings.',
        'Deptford and Catford families, sisters, and beginners',
        'kids',
        [
            ['q' => 'Can Lewisham children take class after after-school club at 5:30?', 'a' => 'Book 6pm or later with a snack buffer. Hungry children do not recite well.'],
            ['q' => 'Do you teach mixed African and Turkish households?', 'a' => 'Yes. Same recitation rules, individual starting points.'],
            ['q' => 'Is a free trial available?', 'a' => 'Yes, in UK time.'],
        ],
    ]),

    rq_uk_loc(['barnet', 'Barnet', 'london_borough', 'North London', false,
        ['Colindale', 'Edgware', 'Hendon', 'Burnt Oak', 'Finchley', 'Golders Green edge'],
        'Barnet’s Muslim communities in Colindale, Edgware, and Hendon include Indian, Pakistani, Afghan, and Arab families in a large outer-north London borough.',
        'Barnet distances are suburban. The “local” madrasa can still be a car ride. Online 1-1 Quran classes remove that school-run extra leg.',
        'Many children already have academic tutors. We place Quran in a realistic early-evening slot so the week remains humane.',
        'Hifz, Tajweed, and female tutors are available on UK time.',
        'Colindale families, Edgware households, and sisters',
        'hifz',
        [
            ['q' => 'Can Edgware children keep Hifz during grammar-school prep?', 'a' => 'Reduce new sabaq, protect revision. We will not pretend exam term is a normal Hifz term.'],
            ['q' => 'Do Afghan families in Colindale start from Qaida or Quran?', 'a' => 'We assess live. Many children read some Quran and still need letter repair.'],
            ['q' => 'Are female teachers available in Hendon?', 'a' => 'Online female tutors are available regardless of the exact Barnet ward.'],
        ],
    ]),

    rq_uk_loc(['hillingdon', 'Hillingdon', 'london_borough', 'West London', false,
        ['Hayes', 'West Drayton', 'Uxbridge', 'Yiewsley', 'Yeading', 'Heathrow villages'],
        'Hillingdon’s Muslim population is strong in Hayes and West Drayton, with airport-linked shift work and families who moved west from Ealing and Hounslow.',
        'Hillingdon parents on Heathrow rotas need Quran classes that can move. Live online teaching is easier to retarget than a mosque hall in Hayes that starts whether or not overtime ended.',
        'We still aim for two repeating weekly anchors so children have rhythm.',
        'Qaida, Tajweed, Hifz, and female tutors on UK time.',
        'Hayes families, airport-shift households, and sisters',
        'tajweed',
        [
            ['q' => 'Can Hayes shift workers change times when the roster flips?', 'a' => 'Give us notice and we try to keep the same tutor on a new UK slot.'],
            ['q' => 'Do children in West Drayton need to travel to Southall for teaching?', 'a' => 'Not for weekday 1-1. Online keeps the tutor without the A312 run.'],
            ['q' => 'Are weekend-only plans possible?', 'a' => 'Possible, but two shorter weekdays usually produce better Tajweed.'],
        ],
    ]),

    rq_uk_loc(['wolverhampton', 'Wolverhampton', 'city', 'West Midlands', false,
        ['Whitmore Reans', 'Blakenhall', 'All Saints', 'Penn Fields', 'Heath Town', 'Dunstall'],
        'Wolverhampton has a substantial Sikh and Muslim mix; Pakistani and other Muslim families around Blakenhall and Whitmore Reans still need dedicated Quran teaching distinct from the wider Black Country offer.',
        'Wolverhampton parents want recitation classes that do not require a drive into Birmingham. Live online 1-1 lessons keep a qualified tutor in the child’s week locally.',
        'We go steadily through Qaida and Tajweed, with female tutor options.',
        'UK evenings match Black Country school finishes.',
        'Blakenhall families, sisters, and beginners',
        'qaida',
        [
            ['q' => 'Do we need to travel to Birmingham for a specialist Hifz teacher?', 'a' => 'Not if you use online matching. A structured Hifz tutor can teach from the Wolverhampton home.'],
            ['q' => 'Are classes after school on UK time?', 'a' => 'Yes.'],
            ['q' => 'Can siblings share consecutive slots?', 'a' => 'Yes. That is the practical pattern for one device.'],
        ],
    ]),

    rq_uk_loc(['walsall', 'Walsall', 'city', 'West Midlands', false,
        ['Pleck', 'Caldmore', 'Palfrey', 'Chuckery', 'Alumwell', 'Birchills'],
        'Walsall has a significant Muslim community in Caldmore, Palfrey, and Pleck, with Pakistani families and a Black Country industrial timetable.',
        'Walsall households need Quran classes after school that do not collapse when a parent’s shift overruns. Home live lessons are easier to save than a hall that locks the door at six.',
        'Private Tajweed helps children who recite with confidence in the community but still miss rules.',
        'Female tutors and Hifz plans are available.',
        'Caldmore families, sisters, and school children',
        'tajweed',
        [
            ['q' => 'Can Walsall children keep mosque and add online Tajweed?', 'a' => 'Yes. Share the mosque lesson so we reinforce it.'],
            ['q' => 'Do you teach in UK time?', 'a' => 'Yes. Same timezone as Birmingham.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes, on request.'],
        ],
    ]),

    rq_uk_loc(['sandwell', 'Sandwell', 'city', 'West Midlands', false,
        ['Smethwick', 'West Bromwich', 'Oldbury', 'Tipton', 'Wednesbury', 'Cape Hill'],
        'Sandwell, especially Smethwick and Cape Hill, has one of the West Midlands’ important Muslim populations, sitting between Birmingham and Wolverhampton.',
        'Sandwell parents often live close to community recitation and still want 1-1 Tajweed. Online lessons give each child a private ear without another minibus across the borough.',
        'We teach Qaida through Hifz with female tutor options on UK evenings.',
        'Cape Hill and Smethwick families are used to busy households; consecutive sibling slots keep order.',
        'Smethwick families, sisters, and Hifz students',
        'hifz',
        [
            ['q' => 'Is Sandwell a town or a borough on this page?', 'a' => 'We treat Sandwell as the local authority people search, with areas like Smethwick named in the copy so the page is locally specific.'],
            ['q' => 'Can three children in Cape Hill take class one after another?', 'a' => 'Yes. Private consecutive slots, not one group call.'],
            ['q' => 'Do you offer female Hifz teachers?', 'a' => 'Request at trial so we match before week one.'],
        ],
    ]),

    rq_uk_loc(['stoke-on-trent', 'Stoke-on-Trent', 'city', 'Staffordshire', false,
        ['Cobridge', 'Hanley', 'Shelton', 'Smallthorne', 'Burslem', 'Fenton'],
        'Stoke-on-Trent has a notable Pakistani Muslim community around Cobridge and Shelton, in a six-town city where travel between areas is part of daily life.',
        'Stoke families should not have to cross towns after dark for a suitable Quran class. Live online 1-1 teaching keeps recitation at home in Cobridge or Hanley.',
        'We emphasise foundations: Qaida, slow Tajweed, then Hifz if the revision is honest.',
        'Female tutors and UK evenings are available.',
        'Cobridge families, sisters, and beginners',
        'qaida',
        [
            ['q' => 'Can a child in Fenton keep the same teacher as a cousin in Cobridge?', 'a' => 'They can follow similar UK times. Each child still needs their own slot and plan.'],
            ['q' => 'Do you teach after Staffordshire school hours?', 'a' => 'Yes, on UK time.'],
            ['q' => 'Is Hifz available?', 'a' => 'Yes, if reading is ready. We will not start heavy memorisation on an unsteady Qaida.'],
        ],
    ]),

    rq_uk_loc(['telford', 'Telford', 'city', 'Shropshire', false,
        ['Malinslee', 'Dawley', 'Wellington', 'Madeley', 'Sutton Hill', 'Town centre'],
        'Telford’s Muslim community is smaller and more spread across a new town of long internal drives, with families who often relocated from the West Midlands for housing.',
        'Telford parents feel the gap when they leave Birmingham’s dense mosque network. Online 1-1 Quran classes restore weekly recitation without waiting for a new local circle to form.',
        'Children keep the same tutor through house moves inside the new town.',
        'Qaida, Tajweed, and female tutors on UK evenings.',
        'West-Midlands movers, sisters, and children in spread-out estates',
        'kids',
        [
            ['q' => 'We moved from Birmingham to Telford. Can classes start before we find a mosque?', 'a' => 'Yes. Weekday recitation can begin immediately after trial, while you settle jumu’ah locally.'],
            ['q' => 'Are drives across Telford a problem for madrasa?', 'a' => 'They are a common reason families drop midweek class. Home live lessons remove the drive.'],
            ['q' => 'Do you teach UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['loughborough', 'Loughborough', 'city', 'Leicestershire', false,
        ['Town centre', 'Shelthorpe', 'Thorpe Acre', 'Campus area', 'Nanpantan', 'Dishley'],
        'Loughborough combines a settled Muslim town community with a large student population, sitting close to Leicester’s bigger mosque networks without matching their density.',
        'Loughborough needs family Qaida after school and student Tajweed around lab hours. Live 1-1 online teaching serves both without forcing one hall timetable.',
        'Students can continue from home cities in the holidays on the same UK timezone.',
        'Female tutors are available.',
        'Town families, university students, and sisters',
        'tajweed',
        [
            ['q' => 'Can Loughborough students keep class during exam weeks?', 'a' => 'We can shorten or pause, then resume with the same tutor.'],
            ['q' => 'Do town children use different hours from campus students?', 'a' => 'Usually yes. Children book after school; students often prefer later UK evenings.'],
            ['q' => 'Is Leicester timezone the same?', 'a' => 'The whole UK uses the same zone. Only the school-run differs.'],
        ],
    ]),

    rq_uk_loc(['rotherham', 'Rotherham', 'city', 'South Yorkshire', false,
        ['Eastwood', 'Wellgate', 'Ferham', 'Masbrough', 'Clifton', 'East Dene'],
        'Rotherham has a significant Pakistani Muslim community adjacent to Sheffield, with families who sometimes travel between the two for work and mosque life.',
        'Rotherham parents want Quran classes that do not depend on a Sheffield evening drive. Live online 1-1 teaching keeps Tajweed in the Rotherham home.',
        'We go patiently with children who already recite in community settings but need rules cleaned.',
        'Female tutors and Qaida are available on UK time.',
        'Eastwood families, sisters, and school children',
        'tajweed',
        [
            ['q' => 'Can we stay with a teacher if we sometimes visit family in Sheffield?', 'a' => 'Yes. The class is online. Keep UK time and a quiet room wherever you are.'],
            ['q' => 'Do you teach after South Yorkshire school hours?', 'a' => 'Yes.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes, on request.'],
        ],
    ]),

    rq_uk_loc(['doncaster', 'Doncaster', 'city', 'South Yorkshire', false,
        ['Town centre', 'Hyde Park', 'Balby', 'Hexthorpe', 'Wheatley', 'Bentley'],
        'Doncaster’s Muslim community is smaller than Sheffield’s, with families who feel the gap in specialist madrasa options more sharply.',
        'Doncaster parents need a reliable Quran teacher on UK evenings more than they need a huge local market. Online 1-1 classes provide that reliability.',
        'When the nearest suitable sisters’ class is in another town, a female online tutor is the practical answer.',
        'Qaida, Tajweed, and Hifz are offered.',
        'Smaller-community families, sisters, and beginners',
        'qaida',
        [
            ['q' => 'Is Doncaster too small for Hifz circles?', 'a' => 'Local options can be limited. Structured online Hifz fills that gap if the child’s reading is ready.'],
            ['q' => 'Can new Muslims in Doncaster join?', 'a' => 'Yes. We start from letters and short surahs with adult or child pacing as needed.'],
            ['q' => 'Are classes on UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['salford', 'Salford', 'city', 'Greater Manchester', false,
        ['Pendleton', 'Eccles', 'Broughton', 'Ordsall', 'Swinton', 'MediaCity'],
        'Salford sits beside Manchester with Muslim families in Broughton and Pendleton and a younger professional/student mix around MediaCity.',
        'Salford households should not have to cross into Manchester every weekday for Quran class. Live online 1-1 teaching keeps recitation in the Salford home.',
        'Shift-like media hours and school runs can both be planned privately, unlike a single mosque timetable.',
        'Female tutors and Tajweed repair are available.',
        'Broughton families, MediaCity professionals, and sisters',
        'tajweed',
        [
            ['q' => 'Can Salford professionals book later than school children?', 'a' => 'Yes. Adult slots often sit later in the UK evening.'],
            ['q' => 'Do Broughton children already in Manchester madrasa still benefit?', 'a' => 'Weekday online precision still helps. Share the madrasa homework.'],
            ['q' => 'Is the timezone Manchester’s?', 'a' => 'UK time for both.'],
        ],
    ]),

    rq_uk_loc(['bury', 'Bury', 'city', 'Greater Manchester', false,
        ['Prestwich', 'Whitefield', 'Bury town', 'Radcliffe', 'Unsworth', 'Fishpool'],
        'Bury borough includes Prestwich and Whitefield, with Jewish and Muslim neighbours and Pakistani families who often look toward Manchester for extra Islamic classes.',
        'Bury parents want Quran teaching that stays in the borough on school nights. Online 1-1 lessons remove the need to drive into Cheetham Hill midweek.',
        'We keep Hifz realistic beside Lancashire/Greater Manchester school homework.',
        'Female tutors are available.',
        'Prestwich and Whitefield families, sisters, and children',
        'hifz',
        [
            ['q' => 'Can Whitefield children avoid a midweek Manchester madrasa run?', 'a' => 'That is a main use of weekday online Tajweed and Hifz.'],
            ['q' => 'Do you teach UK evenings?', 'a' => 'Yes.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['stockport', 'Stockport', 'city', 'Greater Manchester', false,
        ['Heaton Chapel', 'Reddish', 'Edgeley', 'Cheadle', 'Bramhall edge', 'Town centre'],
        'Stockport’s Muslim community is growing among families who moved out of central Manchester for housing, plus longer-settled households in Heaton Chapel and Reddish.',
        'Stockport commuters return on packed rails. A Quran class at home after the school run is more realistic than a Manchester hall at 5:30pm.',
        'We teach Qaida and Tajweed 1-1 on UK time.',
        'Female tutors and sibling consecutive slots are available.',
        'Manchester-mover families, sisters, and primary children',
        'kids',
        [
            ['q' => 'We moved from Longsight to Stockport. Can the online teacher continue?', 'a' => 'Yes. Continuity after a housing move is a core benefit.'],
            ['q' => 'Are after-school slots available?', 'a' => 'Yes. Later evenings if the rail return is late.'],
            ['q' => 'Do you offer Hifz?', 'a' => 'Yes, when reading is ready.'],
        ],
    ]),

    rq_uk_loc(['wigan', 'Wigan', 'city', 'Greater Manchester', false,
        ['Town centre', 'Pemberton', 'Ashton-in-Makerfield', 'Hindley', 'Golborne', 'Standish edge'],
        'Wigan’s Muslim community is smaller than Bolton’s or Manchester’s, so specialist madrasa choice is thinner and online teaching matters more.',
        'Wigan parents need a dependable Quran tutor on UK evenings without a long drive toward Bolton. Live 1-1 classes provide that.',
        'New Muslims and children who are one of few in their school year are welcome.',
        'Qaida and Tajweed with female tutor options.',
        'Smaller-community families, sisters, and beginners',
        'qaida',
        [
            ['q' => 'Is Wigan too small for a local female Hifz teacher?', 'a' => 'Local specialists can be scarce. Online matching is built for that.'],
            ['q' => 'Can we start a complete beginner?', 'a' => 'Yes. Qaida from letters, at the child’s pace.'],
            ['q' => 'Are classes on UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['warrington', 'Warrington', 'city', 'Cheshire', false,
        ['Bewsey', 'Dallam', 'Town centre', 'Westbrook', 'Birchwood', 'Latchford'],
        'Warrington sits between Liverpool and Manchester with a growing Muslim population of commuters and families who want Islamic education without assuming a mill-town density of mosques.',
        'Warrington parents often work along the M62. Online 1-1 Quran classes start at home when the household is back, not when a Manchester timetable dictates.',
        'We teach Qaida, Tajweed, and Hifz on UK evenings.',
        'Female tutors are available.',
        'Commuter families, sisters, and children in a mid-sized community',
        'tajweed',
        [
            ['q' => 'Can M62 commuters book after 7pm?', 'a' => 'Later UK evenings are often the honest choice. Book what you can keep.'],
            ['q' => 'Do you teach beginners in Warrington?', 'a' => 'Yes. Many children here do not have a walkable daily madrasa.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['wirral', 'Wirral', 'city', 'Merseyside', false,
        ['Birkenhead', 'Tranmere', 'Rock Ferry', 'Wallasey', 'Liscard', 'Bebington'],
        'Wirral’s Muslim community is smaller and more dispersed than Liverpool’s city-side, with families in Birkenhead who may cross the water for jumu’ah.',
        'Wirral parents should not have to tunnel under the Mersey on a school night for Quran class. Live online 1-1 teaching keeps recitation in Birkenhead or Wallasey.',
        'A female tutor can be matched even when a local sisters’ circle is limited.',
        'Qaida and Tajweed on UK evenings.',
        'Birkenhead families, sisters, and smaller-community children',
        'qaida',
        [
            ['q' => 'Do we need to go into Liverpool for quality Tajweed teaching?', 'a' => 'Not midweek. Online 1-1 is designed so Wirral children can learn at home.'],
            ['q' => 'Can classes continue if we visit family in Liverpool?', 'a' => 'Yes, if you still have a quiet UK-time slot and a device.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['gateshead', 'Gateshead', 'city', 'North East England', false,
        ['Bensham', 'Teams', 'Saltwell', 'Deckham', 'Town centre', 'Metrocentre edge'],
        'Gateshead sits across the Tyne from Newcastle with a smaller Muslim community and families who often look to Newcastle’s West End for Islamic services.',
        'Gateshead parents need weekday Quran class without a rush-hour bridge crossing. Online 1-1 lessons keep the tutor in the Gateshead home.',
        'Winter evenings in the North East are dark early; home class is safer and more consistent than a bus into Newcastle.',
        'Qaida, Tajweed, and female tutors on UK time.',
        'Families who would otherwise skip midweek Newcastle madrasa, sisters, and beginners',
        'kids',
        [
            ['q' => 'Can Gateshead children avoid a midweek trip into Newcastle?', 'a' => 'Yes. That is a primary reason to book online weekday Tajweed.'],
            ['q' => 'Do you follow UK time in the North East?', 'a' => 'Yes. GMT/BST.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['sunderland', 'Sunderland', 'city', 'North East England', false,
        ['Millfield', 'Hendon', 'City centre', 'Ashbrooke', 'Pallion', 'Southwick'],
        'Sunderland’s Muslim community is modest compared with Leeds or Manchester, which makes a reliable private Quran teacher more valuable, not less.',
        'Sunderland families and students need live 1-1 classes on UK evenings because specialist local options can be thin. Online matching fills that gap.',
        'We welcome children who are among the few Muslims in their school year.',
        'Qaida and Tajweed with female tutor options.',
        'Smaller-community families, university students, and sisters',
        'qaida',
        [
            ['q' => 'Is Sunderland too small for this kind of page to be useful?', 'a' => 'A smaller community is exactly where a dedicated online tutor helps most, because hall options are fewer.'],
            ['q' => 'Can university students join?', 'a' => 'Yes, with later UK slots and exam-week flexibility.'],
            ['q' => 'Do you teach complete beginners?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['middlesbrough', 'Middlesbrough', 'city', 'North East England', false,
        ['University area', 'Linthorpe', 'Grove Hill', 'North Ormesby', 'Ayresome', 'Town centre'],
        'Middlesbrough has a diverse and growing Muslim population including Arab, South Asian, and student communities, distinct from Newcastle’s West End pattern.',
        'Middlesbrough parents and students need Quran classes that fit Teesside school hours and university timetables. Live 1-1 online teaching does that in UK time.',
        'New Muslims are a visible part of the town’s story; we teach without assuming a childhood madrasa.',
        'Female tutors available.',
        'Families, students, and new Muslims',
        'tajweed',
        [
            ['q' => 'Do you teach new Muslims in Middlesbrough?', 'a' => 'Yes. Letters, pronunciation, and short surahs with respectful adult pacing.'],
            ['q' => 'Can children start Qaida after school?', 'a' => 'Yes, on UK evenings.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['southampton', 'Southampton', 'city', 'Hampshire', false,
        ['Portswood', 'Bevois Valley', 'St Marys', 'Shirley', 'Bitterne', 'University halls'],
        'Southampton has a long-standing Yemeni and Somali presence around St Marys and a large student population in Portswood, creating two different Quran-class needs in one port city.',
        'Southampton families want steady after-school Qaida; students want Tajweed that survives maritime and university rotas. Live 1-1 online teaching serves both.',
        'A private tutor can pause for exam season without losing the student’s place in a hall.',
        'Female tutors and UK evenings are available.',
        'St Marys families, Portswood students, and sisters',
        'tajweed',
        [
            ['q' => 'Can Yemeni-heritage children in St Marys who already hear Arabic still need Tajweed?', 'a' => 'Yes. Home Arabic does not guarantee rule-based recitation.'],
            ['q' => 'Do university students book later slots?', 'a' => 'Usually. Children take after-school UK times; students often take evenings.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['portsmouth', 'Portsmouth', 'city', 'Hampshire', false,
        ['Southsea', 'Somerstown', 'Fratton', 'North End', 'Copnor', 'City centre'],
        'Portsmouth’s Muslim community is smaller and island-constrained, with naval-shift families and students who cannot assume a dense madrasa network.',
        'Portsmouth parents need a Quran teacher who is not dependent on a ferry-timed hall. Live online 1-1 classes run from the Southsea or Fratton home on UK evenings.',
        'We teach beginners and new Muslims without requiring a large peer group.',
        'Female tutors available.',
        'Naval-shift families, students, and smaller-community children',
        'qaida',
        [
            ['q' => 'Can naval-shift parents change class times?', 'a' => 'Give us roster notice. We try to keep the same tutor on a new UK slot.'],
            ['q' => 'Is Portsmouth too small for Hifz?', 'a' => 'Local circles may be limited. Online Hifz is available if reading is ready.'],
            ['q' => 'Do you teach UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['brighton', 'Brighton', 'city', 'East Sussex', false,
        ['City centre', 'Kemptown', 'London Road', 'Bevendean', 'Moulsecoomb', 'Hove border'],
        'Brighton and Hove have a smaller, more professional and student-heavy Muslim community than northern mill towns, with children who may have few Muslim classmates.',
        'Brighton families need private, calm Quran teaching. Live 1-1 online lessons are often more comfortable than being the only child in a mixed-age circle.',
        'Students can flex around Sussex term dates. We stay on UK time.',
        'Female tutors and adult Tajweed are important here.',
        'Professionals, students, new Muslims, and small-community children',
        'tajweed',
        [
            ['q' => 'Our child is one of very few Muslims in their Brighton school. Will class still work?', 'a' => 'Yes. 1-1 teaching does not need a large peer group and can explain basics without embarrassment.'],
            ['q' => 'Do you teach new Muslims at university?', 'a' => 'Yes, with adult pacing and short surahs.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['swindon', 'Swindon', 'city', 'Wiltshire', false,
        ['Central Swindon', 'Walcot', 'Parks', 'Eastville', 'Westlea', 'North Swindon'],
        'Swindon has a growing Muslim population of rail and manufacturing workers and families who relocated along the M4, with fewer historic madrasas than Leicester or Birmingham.',
        'Swindon parents need a Quran class that exists this term, not after a waiting list. Live online 1-1 teaching can start after a free UK-time trial.',
        'Children keep the same tutor if the family later moves within the M4 corridor.',
        'Qaida, Tajweed, and female tutors on UK evenings.',
        'M4-corridor families, sisters, and beginners',
        'kids',
        [
            ['q' => 'Local madrasa is full. Can we start online anyway?', 'a' => 'Yes. That is a common Swindon reason to enrol.'],
            ['q' => 'Do you teach after school on UK time?', 'a' => 'Yes.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['norwich', 'Norwich', 'city', 'Norfolk', false,
        ['City centre', 'University area', 'Mile Cross', 'Earlham', 'Lakenham', 'Sprowston edge'],
        'Norwich has a smaller East Anglian Muslim community of families, professionals, and UEA students, far from the density of London or Birmingham.',
        'Norwich parents and students need a private Quran teacher because specialist local options are limited. Online 1-1 classes on UK evenings are the practical path.',
        'We teach children who may be the only Muslim in their year group, with patience and no assumed madrasa culture.',
        'Female tutors available.',
        'East Anglian families, students, and new Muslims',
        'qaida',
        [
            ['q' => 'Is Norwich too far from large Muslim cities for this to work?', 'a' => 'Distance is why online works. The tutor is on the call regardless of Norfolk geography.'],
            ['q' => 'Can UEA students join?', 'a' => 'Yes, with exam-week flexibility.'],
            ['q' => 'Do you teach complete beginners?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['ipswich', 'Ipswich', 'city', 'Suffolk', false,
        ['Town centre', 'Westgate', 'Whitton', 'Chantry', 'Stoke', 'University Campus Suffolk area'],
        'Ipswich has a growing but still modest Muslim community in Suffolk, with families who cannot assume a walkable daily madrasa.',
        'Ipswich parents need consistent Quran lessons on UK evenings. Live 1-1 online teaching provides a specialist tutor without a trip toward London.',
        'Sisters can request female teachers even when a local circle is not running.',
        'Qaida and Tajweed first; Hifz if reading is ready.',
        'Suffolk families, sisters, and beginners',
        'kids',
        [
            ['q' => 'Can we start if there is no suitable local madrasa this year?', 'a' => 'Yes. Online Qaida is designed for that gap.'],
            ['q' => 'Are classes after Suffolk school hours?', 'a' => 'Yes, UK time.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['southend-on-sea', 'Southend-on-Sea', 'city', 'Essex', false,
        ['Southend', 'Westcliff', 'Leigh-on-Sea', 'Prittlewell', 'Shoeburyness', 'Southchurch'],
        'Southend-on-Sea has an Essex coastal Muslim community of commuters and families, smaller than East London boroughs but linked to them by c2c rail.',
        'Southend parents who left Newham or Redbridge for the coast often lose their old madrasa. Online 1-1 Quran classes keep the same quality of teaching after the move.',
        'Commuter returns from Fenchurch Street run late. Book the hour the child is actually home in Westcliff.',
        'Female tutors and Qaida on UK evenings.',
        'East-London movers, commuter families, and sisters',
        'tajweed',
        [
            ['q' => 'We moved from Ilford to Westcliff. Can online classes replace the old madrasa midweek?', 'a' => 'Yes. Keep jumu’ah locally if you wish, and use weekday online time for Tajweed.'],
            ['q' => 'Are later evenings available after c2c delays?', 'a' => 'Book a realistic UK evening, not a 5pm hope.'],
            ['q' => 'Do you teach beginners?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['hull', 'Hull', 'city', 'East Yorkshire', false,
        ['Spring Bank', 'City centre', 'Newland', 'University area', 'West Hull', 'East Hull'],
        'Kingston upon Hull has a diverse Muslim community including South Asian, Arab, and Eastern European families, with a port-city character unlike West Yorkshire mill towns.',
        'Hull families and students need live 1-1 Quran classes on UK evenings because specialist options can be spread thin across the city. Online teaching concentrates quality in the home.',
        'We welcome new Muslims and children rebuilding recitation after interrupted schooling.',
        'Female tutors available.',
        'Spring Bank families, students, and new Muslims',
        'qaida',
        [
            ['q' => 'Do you teach families with mixed home languages in Hull?', 'a' => 'English is the classroom language. Recitation is Arabic. We start from the child’s level.'],
            ['q' => 'Can university students join from Newland?', 'a' => 'Yes, with headphones and a quieter room than a kitchen at dinner.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['york', 'York', 'city', 'North Yorkshire', false,
        ['City centre', 'University campuses', 'Fulford', 'Clifton', 'Heworth', 'Acomb'],
        'York has a small Muslim community of professionals, students, and families in a tourist city where children may have almost no Muslim peers at school.',
        'York parents need private, respectful Quran teaching. Live 1-1 online lessons avoid the awkwardness of being the only child in a tiny mixed group.',
        'University terms and tourist-season hospitality hours can be planned privately.',
        'Female tutors and adult Tajweed matter here.',
        'Professionals, students, and small-community children',
        'tajweed',
        [
            ['q' => 'Our child has no Muslim classmates in York. Is 1-1 better?', 'a' => 'Usually yes. Private class lets them ask basic questions without embarrassment.'],
            ['q' => 'Can students pause for York exam season?', 'a' => 'Yes, then resume with the same tutor.'],
            ['q' => 'Do you teach UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['swansea', 'Swansea', 'city', 'Wales', false,
        ['City centre', 'Uplands', 'Sandfields', 'St Thomas', 'Sketty', 'University area'],
        'Swansea has a smaller Welsh Muslim community than Cardiff, with students and families who cannot assume a dense madrasa market.',
        'Swansea parents and students need a reliable Quran tutor on UK (Wales) evenings. Live 1-1 online classes provide specialist teaching without a trip to Cardiff.',
        'We teach beginners and sisters who prefer a female teacher at home.',
        'Qaida and Tajweed first.',
        'Families, students, and sisters in a smaller Welsh community',
        'qaida',
        [
            ['q' => 'Do we need to travel to Cardiff for quality teaching?', 'a' => 'Not for weekday 1-1. Online keeps the tutor in Swansea.'],
            ['q' => 'Is the timezone the same as England?', 'a' => 'Yes. Wales uses UK time.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['newport', 'Newport', 'city', 'Wales', false,
        ['Pillgwenlly', 'Maindee', 'City centre', 'Stow Hill', 'Ringland', 'Maesglas'],
        'Newport, Wales, has a growing Muslim community including Somali and South Asian families in Pill and Maindee, distinct from Cardiff even though the cities are close.',
        'Newport parents want Quran classes that stay in the city on school nights rather than depending on a Cardiff commute. Live online 1-1 teaching does that.',
        'We go gently with children who are new to structured recitation.',
        'Female tutors and UK evenings.',
        'Pill and Maindee families, sisters, and beginners',
        'kids',
        [
            ['q' => 'Can Newport children avoid a midweek Cardiff madrasa run?', 'a' => 'Yes. Weekday online Tajweed is for that pattern.'],
            ['q' => 'Do you teach Somali-heritage children in Pill?', 'a' => 'Yes. English explanation, Arabic recitation.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['dundee', 'Dundee', 'city', 'Scotland', false,
        ['City centre', 'Hilltown', 'West End', 'University areas', 'Stobswell', 'Lochee'],
        'Dundee has a smaller Scottish Muslim community than Glasgow, with families and students who need specialist Quran teaching without assuming a Pollokshields-density of mosques.',
        'Dundee parents and students follow Scottish term dates and dark winter afternoons. Live 1-1 online classes still run in UK time, booked around Dundee school finishes.',
        'A female tutor can be matched even when a local sisters’ class is not running this term.',
        'Qaida and Tajweed with optional Hifz.',
        'Scottish families, students, and sisters',
        'qaida',
        [
            ['q' => 'Do you follow Scottish holidays rather than English ones?', 'a' => 'Tell us Dundee dates. We can ease local holiday weeks.'],
            ['q' => 'Can students join from the West End?', 'a' => 'Yes, with a quiet room and headphones.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['aberdeen', 'Aberdeen', 'city', 'Scotland', false,
        ['City centre', 'Tillydrone', 'Old Aberdeen', 'Bridge of Don', 'Garthdee', 'University area'],
        'Aberdeen’s Muslim community includes oil-and-gas professionals, international families, and students, with a more transient pattern than Glasgow’s southside.',
        'Aberdeen households need Quran classes that survive offshore rotas and university terms. Live 1-1 online teaching can move when a parent’s rota moves, while children keep a UK-time backbone.',
        'International families can continue if they relocate within the UK.',
        'Female tutors and beginner Qaida are important.',
        'Professional families, international households, and students',
        'tajweed',
        [
            ['q' => 'Can offshore rotas change adult class times?', 'a' => 'Adults can move slots with notice. Children’s weekly backbone should stay as stable as possible.'],
            ['q' => 'Do you teach children who change schools mid-year because of relocation?', 'a' => 'The online tutor stays, which is the point after an Aberdeen posting change.'],
            ['q' => 'Is Aberdeen on UK time?', 'a' => 'Yes. Scotland uses GMT/BST.'],
        ],
    ]),

    rq_uk_loc(['crawley', 'Crawley', 'city', 'West Sussex', false,
        ['Ifield', 'Langley Green', 'West Green', 'Southgate', 'Three Bridges', 'Furnace Green'],
        'Crawley has a relatively high Muslim population for the south-east, linked to Gatwick employment and families who moved from London for housing.',
        'Crawley parents on airport shifts face the same problem as Hounslow: hall timetables do not care about overtime. Live online Quran classes can retarget while children keep two weekly anchors.',
        'London-mover children keep a qualified tutor without travelling back to a Croydon madrasa midweek.',
        'Female tutors and UK evenings.',
        'Gatwick-shift families, London movers, and sisters',
        'tajweed',
        [
            ['q' => 'Can Gatwick shift workers move class times?', 'a' => 'With notice, we try to keep the same tutor on a new UK slot.'],
            ['q' => 'We moved from south London to Crawley. Can teaching continue immediately?', 'a' => 'Yes. Online weekday recitation does not wait for a new local madrasa place.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['medway', 'Medway', 'city', 'Kent', false,
        ['Gillingham', 'Chatham', 'Rochester', 'Strood', 'Rainham', 'Luton (Medway)'],
        'Medway’s towns — Gillingham, Chatham, Rochester — have a growing Muslim population of London leavers and local families, spread across a wide Kent authority.',
        'Medway parents discover that “nearby” madrasa can still mean a drive through Chatham traffic. Online 1-1 Quran classes keep recitation in the Gillingham or Rochester home.',
        'We teach Qaida and Tajweed on UK evenings with female tutor options.',
        'Siblings can take consecutive slots on one device.',
        'Kent London-leavers, sisters, and school children',
        'kids',
        [
            ['q' => 'Is Medway one city or several towns on this page?', 'a' => 'Medway is the local authority people search. Copy names Gillingham, Chatham, and Rochester so residents recognise their town.'],
            ['q' => 'Can we start if the local madrasa is in another Medway town?', 'a' => 'Yes. Home class removes the cross-town run.'],
            ['q' => 'Do you teach UK time?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['dartford', 'Dartford', 'city', 'Kent', false,
        ['Town centre', 'Temple Hill', 'Newtown', 'Fleet Estate', 'Greenhithe edge', 'Ebbsfleet edge'],
        'Dartford sits on the London-Kent edge with families who moved out of Greenwich and Bexley, plus commuters using Ebbsfleet and the Dartford Crossing pattern of life.',
        'Dartford parents lose walkable East London madrasas after the move. Online 1-1 Quran classes restore weekday recitation immediately.',
        'Crossing traffic makes a midweek return to Woolwich unrealistic. Home class is the honest plan.',
        'Female tutors and Qaida on UK evenings.',
        'London-edge movers, sisters, and primary children',
        'qaida',
        [
            ['q' => 'We moved from Woolwich to Dartford. Can the child keep online Tajweed?', 'a' => 'Yes. That continuity is the point of enrolling online before or after the move.'],
            ['q' => 'Are after-school slots available?', 'a' => 'Yes, on UK time.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['burton-upon-trent', 'Burton upon Trent', 'city', 'Staffordshire', false,
        ['Anglesey', 'Shobnall', 'Upton', 'Stapenhill', 'Winshill', 'Town centre'],
        'Burton upon Trent has a well-known Pakistani Muslim community for a Staffordshire town, with mosque life that is central in Anglesey and Shobnall.',
        'Burton parents often already have weekend madrasa. They use online 1-1 lessons for weekday Tajweed precision and for female teaching at home.',
        'Brewery and warehouse shift patterns in the town can wreck a fixed hall time. Home class is easier to keep.',
        'Hifz is available when reading is ready.',
        'Anglesey families, sisters, and school children',
        'tajweed',
        [
            ['q' => 'Can Burton children keep mosque on Saturday and online on weekdays?', 'a' => 'Yes. Share mosque sabaq so we reinforce it.'],
            ['q' => 'Do shift-working parents need weekend-only class?', 'a' => 'We can use weekends, but two shorter weekdays remain better for Tajweed if the roster allows.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['nuneaton', 'Nuneaton', 'city', 'Warwickshire', false,
        ['Town centre', 'Camp Hill', 'Stockingford', 'Attleborough', 'Weddington', 'Chilvers Coton'],
        'Nuneaton has a growing Muslim community in Warwickshire, close enough to Coventry and Leicester to feel those cities’ pull without matching their madrasa density.',
        'Nuneaton parents need weekday Quran class without a drive into Coventry after school. Live online 1-1 teaching keeps the tutor in the Nuneaton home.',
        'We start many children on Qaida because local beginner slots can be limited.',
        'Female tutors on UK evenings.',
        'Warwickshire families, sisters, and beginners',
        'kids',
        [
            ['q' => 'Can we avoid a midweek drive to Coventry?', 'a' => 'Yes. Weekday online class is designed for that.'],
            ['q' => 'Do you teach complete beginners in Nuneaton?', 'a' => 'Yes. Qaida from letters.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['cambridge', 'Cambridge', 'city', 'Cambridgeshire', false,
        ['City centre', 'Mill Road', 'Romsey', 'Chesterton', 'Arbury', 'University colleges'],
        'Cambridge mixes a settled Muslim community around Mill Road with a global student and academic population that turns over every year.',
        'Cambridge needs family Qaida that survives school runs and student Tajweed that survives dissertation season. Live 1-1 online teaching can be two different plans under one academy.',
        'New Muslims among graduates are welcome and taught at adult pace.',
        'Female tutors available on UK time.',
        'Mill Road families, students, researchers, and new Muslims',
        'tajweed',
        [
            ['q' => 'Can Cambridge students pause for deadlines?', 'a' => 'Yes. Resume with the same tutor rather than ghosting and restarting Qaida later.'],
            ['q' => 'Do town children book different hours from colleges?', 'a' => 'Usually. After-school for children; later evenings for students.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['colchester', 'Colchester', 'city', 'Essex', false,
        ['Town centre', 'Greenstead', 'Highwoods', 'New Town', 'University of Essex area', 'Garrison area'],
        'Colchester has a growing Essex Muslim community of families, students, and garrison-linked households, smaller than London boroughs but rising.',
        'Colchester parents need a Quran teacher on UK evenings without travelling into East London. Live 1-1 online classes provide that specialist attention.',
        'Students at the university can flex around Essex term dates.',
        'Female tutors and Qaida are available.',
        'Essex families, students, and sisters',
        'qaida',
        [
            ['q' => 'Can garrison families continue if posted elsewhere in the UK?', 'a' => 'Yes, if they remain on UK time. The tutor can stay the same.'],
            ['q' => 'Do you teach after school?', 'a' => 'Yes.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['gloucester', 'Gloucester', 'city', 'Gloucestershire', false,
        ['Barton and Tredworth', 'City centre', 'Podsmead', 'Lower Tuffley', 'Kingsholm', 'Longlevens'],
        'Gloucester has a long-established Muslim community around Barton and Tredworth, unusual for the West Country, with Pakistani families and a quieter surrounding county.',
        'Gloucester parents want Tajweed that is as serious as in Birmingham without assuming a Birmingham-sized madrasa market. Live 1-1 online teaching raises the ceiling of what a child can receive at home.',
        'Weekend mosque plus weekday online precision is a strong pattern here.',
        'Female tutors on UK evenings.',
        'Barton and Tredworth families, sisters, and school children',
        'tajweed',
        [
            ['q' => 'Can Gloucester children keep local mosque and add online Tajweed?', 'a' => 'Yes. That combination works well in a city with community mosques but limited 1-1 time.'],
            ['q' => 'Are classes after school on UK time?', 'a' => 'Yes.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['worcester', 'Worcester', 'city', 'Worcestershire', false,
        ['City centre', 'Arboretum', 'Rainbow Hill', 'St Peter’s', 'Warndon', 'University area'],
        'Worcester has a smaller cathedral-city Muslim community of families and students, with fewer specialist madrasa options than the West Midlands conurbation.',
        'Worcester parents need a dependable Quran tutor on UK evenings. Live 1-1 online classes fill the gap without a drive into Birmingham.',
        'We teach beginners who may have almost no Muslim peers at school.',
        'Female tutors available.',
        'Smaller-community families, students, and sisters',
        'qaida',
        [
            ['q' => 'Do we need to travel to Birmingham for Hifz?', 'a' => 'Not if reading is ready. Structured online Hifz can be taught from the Worcester home.'],
            ['q' => 'Can complete beginners start?', 'a' => 'Yes. Qaida from letters.'],
            ['q' => 'Are female tutors available?', 'a' => 'Yes.'],
        ],
    ]),

    rq_uk_loc(['maidstone', 'Maidstone', 'city', 'Kent', false,
        ['Town centre', 'Shepway', 'Park Wood', 'Allington', 'Bearsted edge', 'Tovil'],
        'Maidstone is Kent’s county town with a growing Muslim population of London leavers and local families, spread through suburban estates rather than a single dense ward.',
        'Maidstone parents need weekday Quran class without a trip into Medway or London. Live 1-1 online teaching keeps recitation at home after the Kent school run.',
        'We start many children on Qaida because local beginner provision can lag housing growth.',
        'Female tutors on UK evenings.',
        'Kent families, London leavers, and sisters',
        'kids',
        [
            ['q' => 'We moved from south-east London to Maidstone. Can online Tajweed continue?', 'a' => 'Yes. Continuity after a Kent move is a main benefit.'],
            ['q' => 'Are after-school UK slots available?', 'a' => 'Yes.'],
            ['q' => 'Are female teachers available?', 'a' => 'Yes.'],
        ],
    ]),

];
